### ISSUE TITLE
[Unsorted issue] Tests failed to expand project tree

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#2010] opened 2020-11-12 13:28 UTC
Project Tree was not expanded.
Only seen this happen once.
![image](https://user-images.githubusercontent.com/16451875/98945819-52383400-24f3-11eb-8412-10b84dfc5fd6.png)

**Comment by ScrewTSW** [comment] 2020-11-12 13:28
Seen on prod-preview cluster 2a x1:
****

**Comment by ibuziuk** [comment] 2020-11-12 14:34
duplicate of https://github.com/redhat-developer/rh-che/issues/2007 ?

**Comment by Katka92** [comment] 2020-11-30 08:51
Not reproduced for 18 days. Closing.

**Closed by Katka92** 2020-11-30 08:51 UTC
Labels: kind/bug, kind/fringe-issue, kind/periodic-e2e-test, team/rhche-qe
