### ISSUE TITLE
Inject "app.name" environment variable in Che workspace

### ISSUE THREAD

**Issue by dipak-pawar** [redhat-developer/rh-che#550] opened 2018-02-21 12:49 UTC
Boosters have a special profile which [defines system property ](https://github.com/snowdrop/spring-boot-http-booster/blob/master/pom.xml#L105) called `app.name` set for integration tests execution (failsafe). This is customizable, as the user can name his project anyhow he wants while using quickstart wizard. 

The same property is then used as a service name when injecting [`@RouteUrl`](https://github.com/snowdrop/spring-boot-http-booster/blob/master/src/test/java/io/openshift/booster/OpenShiftIT.java#L33) in the integration test itself. 
This works fine if you are running tests with `maven`. This however, does not work in Che as the property is not recognized, because it's not set as env variable or system property.

However we can get this value by running `mvn help:effective-pom | grep -oPm1 "(?<=<app.name>)[^<]+"` from maven project's root dir.

If we inject this environment variable in Che workspace while importing project in che workspace,  user can run `openshiftIT` test from Che by running `mvn clean package fabric8:build fabric8:resource` upfront.

I started thread for renaming `app.name` to `APP_NAME` from all boosters. Once booster guys are agree to rename it, we have to inject `APP_NAME` 

This needs to be done for https://github.com/arquillian/arquillian-cube/issues/991

**Comment by bartoszmajsak** [comment] 2018-02-21 14:22
At the same time, we are discussing other solutions with Booster teams. The only thing we would like to hear from you guys is the feasibility of this approach.

**Comment by ibuziuk** [comment] 2018-02-21 16:29
@bartoszmajsak @dipak-pawar am I correct that the issue is about analyzing pom.xml on the fly during project import into Che and setting  env var if property was found?

**Comment by ibuziuk** [comment] 2019-08-13 14:35
boosters are not used since due to openshift.io transformation to new version of SaaS. Closing

**Closed by ibuziuk** 2019-08-13 14:35 UTC
Labels: kind/enhancement, severity/P2
