### ISSUE TITLE
Workspace pods stuck in running state

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1417] opened 2019-05-20 12:39 UTC
**Issue problem:** 
There are some pods which are stuck in starting and running states that are not associated to any workspace in the database, therefore they cannot be removed.

These pods actually consume resources and therefore they are preventing us to starting new workspaces in their place.

**Red Hat Che version:** 

version: 7.0.0-beta-4.0
Che-Theia@7bccaab using Theia@7bccaab

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

This is an intermittent issue.
* Create workspace
* Start workspace
* Wait for workspace to get reported as running by openshift
* Stop workspace
* Wait for workspace to be stopped
* Delete workspace
* Wait for workspace to be deleted
* Repeat

Very rarely it happens that the workspace pods on cluster get disassociated with the workspace in che-master database and will not get removed as the workspace is deleted.

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Affected account**
`osiotest-workspace-2` running a workspace startup test with che7 stack and PVC volume
![58003331-d49f8d80-7ae0-11e9-84b5-ed310157653f](https://user-images.githubusercontent.com/16451875/58022309-7dfc7880-7b0d-11e9-98e4-f58e28f13f43.png)

**Comment by ibuziuk** [comment] 2019-05-20 12:43
> are not associated to any workspace in the database

@ScrewTSW Could you please clarify how you get to this conclusion?

**Comment by ScrewTSW** [comment] 2019-05-20 12:45
@ibuziuk Well since there are no workspaces visible when I log in to che with the account and look at the dashboard, I would assume the che-master thinks there are no workspaces but there are still running pods stuck on openshift

**Comment by ibuziuk** [comment] 2019-05-20 12:46
could you provide pod specs ?

**Comment by ScrewTSW** [comment] 2019-05-20 14:43
![firefox_2019-05-20_14-55-04](https://user-images.githubusercontent.com/16451875/58030193-6a0d4280-7b1e-11e9-8b26-019fe3a43e88.png)
![firefox_2019-05-20_14-55-20](https://user-images.githubusercontent.com/16451875/58030195-6aa5d900-7b1e-11e9-8d4e-920957fb4dcf.png)
![firefox_2019-05-20_14-55-33](https://user-images.githubusercontent.com/16451875/58030196-6aa5d900-7b1e-11e9-9157-e15611a6faf3.png)
![firefox_2019-05-20_14-55-44](https://user-images.githubusercontent.com/16451875/58030197-6aa5d900-7b1e-11e9-853f-cd8517d106f3.png)
![firefox_2019-05-20_16-39-27](https://user-images.githubusercontent.com/16451875/58030198-6b3e6f80-7b1e-11e9-9682-a158907c669c.png)
![firefox_2019-05-20_16-42-53](https://user-images.githubusercontent.com/16451875/58030200-6b3e6f80-7b1e-11e9-8d0b-4de6f46d0b61.png)

**Comment by ScrewTSW** [comment] 2019-05-20 14:44
The workspace logs don't seem to have anything suspicious in them.

**Comment by ibuziuk** [comment] 2019-05-22 10:24
prod pods have been restarted and I can not  reproduce the issue anymore

**Comment by ScrewTSW** [comment] 2019-05-22 10:44
we still have another four accounts which are stuck with pods (ephemeral) since yesterday.
One account (namely osiotest-workspace-eph-1b) only have a `ws` pod without the `jwtproxy`
here are the kibana logs:
```
May 20th 2019, 09:59:26.404 | {"@timestamp":"2019-05-20T07:59:26.404+00:00","@version":1,"message":"Workspace 'workspacencar1o0gx6jlfpc4' removed by user 'osiotest-workspace-eph-1b'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-6","level":"INFO","level_value":20000,"identity_id":"c820f874-3fbb-44ec-a312-eefa556ff1ae"}
-- | --

  | May 20th 2019, 09:59:26.151 | {"@timestamp":"2019-05-20T07:59:26.150+00:00","@version":1,"message":"Could not get runtimeIdentity for workspace 'workspacencar1o0gx6jlfpc4', and so cannot verify if current subject 'c820f874-3fbb-44ec-a312-eefa556ff1ae' owns workspace","logger_name":"com.redhat.che.multitenant.Fabric8OpenShiftClientFactory","thread_name":"http-nio-8080-exec-6","level":"WARN","level_value":30000,"identity_id":"c820f874-3fbb-44ec-a312-eefa556ff1ae"}

  | May 20th 2019, 09:59:18.104 | {"@timestamp":"2019-05-20T07:59:18.104+00:00","@version":1,"message":"Error occurred during stopping of runtime 'workspacencar1o0gx6jlfpc4:default:c820f874-3fbb-44ec-a312-eefa556ff1ae' by user 'osiotest-workspace-eph-1b'. Error: Error(s) occurs while cleaning up the namespace. Failed to start websocket","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"WorkspaceSharedPool-1","level":"ERROR","level_value":40000,"stack_trace":"org.eclipse.che.api.workspace.server.spi.InfrastructureException: Error(s) occurs while cleaning up the namespace. Failed to start websocket\n\tat org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:192)\n\tat org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:100)\n\tat org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:618)\n\tat org.eclipse.che.core.tracing.TracingInterceptor.invoke(TracingInterceptor.java:60)\n\tat org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:177)\n\tat org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:824)\n\tat org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)\n\tat java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)\n\tat io.opentracing.contrib.concurrent.TracedRunnable.run(TracedRunnable.java:26)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","identity_id":"c820f874-3fbb-44ec-a312-eefa556ff1ae"}
  | May 20th 2019, 09:59:12.373 | {"@timestamp":"2019-05-20T07:59:12.373+00:00","@version":1,"message":"Workspace 'osiotest-workspace-eph-1b/1558338536580' with id 'workspacencar1o0gx6jlfpc4' is stopping by user 'osiotest-workspace-eph-1b'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-25","level":"INFO","level_value":20000,"identity_id":"c820f874-3fbb-44ec-a312-eefa556ff1ae"}

  | May 20th 2019, 09:59:09.997 | {"@timestamp":"2019-05-20T07:59:09.997+00:00","@version":1,"message":"Workspace 'osiotest-workspace-eph-1b:1558338536580' with id 'workspacencar1o0gx6jlfpc4' started by user 'osiotest-workspace-eph-1b'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"WorkspaceSharedPool-0","level":"INFO","level_value":20000,"identity_id":"c820f874-3fbb-44ec-a312-eefa556ff1ae"}

  | May 20th 2019, 09:58:30.407 | {"@timestamp":"2019-05-20T07:58:30.407+00:00","@version":1,"message":"Starting workspace 'osiotest-workspace-eph-1b/1558338536580' with id 'workspacencar1o0gx6jlfpc4' by user 'osiotest-workspace-eph-1b'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceRuntimes","thread_name":"http-nio-8080-exec-15","level":"INFO","level_value":20000,"identity_id":"c820f874-3fbb-44ec-a312-eefa556ff1ae"}

  | May 20th 2019, 09:58:20.506 | {"@timestamp":"2019-05-20T07:58:20.506+00:00","@version":1,"message":"Workspace 'osiotest-workspace-eph-1b/1558338536580' with id 'workspacencar1o0gx6jlfpc4' created by user 'osiotest-workspace-eph-1b'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-25","level":"INFO","level_value":20000,"identity_id":"c820f874-3fbb-44ec-a312-eefa556ff1ae"}
```

**Comment by ScrewTSW** [comment] 2019-05-22 10:52
affected accounts:
`osiotest-workspace-eph-1a`
`osiotest-workspace-eph-1b`
`osiotest-workspace-eph-2`
`osiotest-workspace-eph-2a-new`

prod-preview account seems to be unaffected.

I am only preserving the `1a` account. We need to run these tests and I cannot afford to provision new accounts every time this happens. I have implemented a reset environment feature into our tests in case they fail, so that we may be running more stable and collect statistics

`osiotest-workspace-eph-1b`: `workspacencar1o0gx6jlfpc4`
![Screenshot_20190522_122228](https://user-images.githubusercontent.com/16451875/58168924-baf07880-7c8f-11e9-8a8b-e2c8888cf8f4.png)
![Screenshot_20190522_122242](https://user-images.githubusercontent.com/16451875/58168928-bd52d280-7c8f-11e9-9e56-02e8ec91c53c.png)

`osiotest-workspace-eph-2a-new` : `workspacel63cox80v79v1q4p`
![Screenshot_20190522_122114](https://user-images.githubusercontent.com/16451875/58169062-0acf3f80-7c90-11e9-81a6-1be05ac0c9e1.png)
![Screenshot_20190522_122136](https://user-images.githubusercontent.com/16451875/58169065-0c990300-7c90-11e9-9981-6e0cd893a9f5.png)

`osiotest-workspace-eph-2` : `workspace546mvbyk15uxkv34`
![Screenshot_20190522_121905](https://user-images.githubusercontent.com/16451875/58169107-3b16de00-7c90-11e9-9dda-d67c43492d2c.png)
![Screenshot_20190522_121927](https://user-images.githubusercontent.com/16451875/58169109-3ce0a180-7c90-11e9-9b08-d035b0130a4e.png)

`osiotest-workspace-eph-1a` : `workspacenxtfw61625twausi`
![Screenshot_20190522_094156](https://user-images.githubusercontent.com/16451875/58169168-639ed800-7c90-11e9-815e-6d7485489a59.png)
![Screenshot_20190522_121751](https://user-images.githubusercontent.com/16451875/58169173-66013200-7c90-11e9-8eda-7a065c4d61b3.png)

**Comment by ScrewTSW** [comment] 2019-06-24 10:54
![image](https://user-images.githubusercontent.com/16451875/60013582-193dbc00-967f-11e9-969c-b99e8e5e0409.png)
Another worksapce pod stuck for the account `osio-ci-preview-testper`

We need this account so I've reset the environment

**Comment by Katka92** [comment] 2019-07-15 04:28
Another worksapce has pod stuck. Happened on 1a for user `osiotest1a`. I'll reset environment because we need this for perodic tests.
![Screenshot from 2019-07-15 06-26-45](https://user-images.githubusercontent.com/29278800/61195657-b06bc180-a6c9-11e9-82c3-eb28b8ce949e.png)

**Comment by Katka92** [comment] 2019-07-15 09:46
The accounts that were left for investigations were decommissioned. Please do **NOT RESET** account when it occurs again and post it there so developers can investigate.

**Comment by ibuziuk** [comment] 2019-11-04 09:52
Closing since this is not reproducible anymore after 7.3.1 update

**Closed by ibuziuk** 2019-11-04 09:52 UTC
Labels: kind/bug
