### ISSUE TITLE
Implement NotificationContainer and Notification objects for TS selenium tests

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1759] opened 2020-01-14 10:45 UTC
**Description:**
For better implementation of selenium tests we should split Notifications away from Ide class.

We should implement NotificationContainer to represent the notification overlay since it's separate from Ide and implement Notification class which would contain methods and differentiation between notification types (info, confirm, open link)

**Comment by Katka92** [comment] 2020-01-27 13:18
This issue should be placed in upstream, not downstream. Please consider closing it here.

**Comment by ScrewTSW** [comment] 2020-02-27 08:44
:+1:

**Comment by Katka92** [comment] 2020-05-18 12:13
Duplicate of upstream issue. Closing.

**Closed by Katka92** 2020-05-18 12:13 UTC
Labels: kind/enhancement, severity/P2, status/in-progress, team/rhche-qe
