### ISSUE TITLE
Che: context assist HTTP 401

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#94] opened 2017-06-07 04:41 UTC
_From @burrsutter on June 6, 2017 23:49_

https://screencast.com/t/549bv3F2

Using the Vert.x Basic template and 
router.
looking at the methods of the Vert.x router - they all pop-up HTTP 401

_Copied from original issue: openshiftio/openshift.io#201_

**Comment by joshuawilson** [comment] 2017-06-07 04:41
This issue was moved to fabric8io/fabric8-ui#1461

**Comment by l0rd** [comment] 2017-07-19 15:54
The (temporary) solution is to remove authentication for some http requests. But we need to open a issue on upstream Che to solve the problem and in any case that issue does not exist when we you a language server.

**Comment by davidfestal** [comment] 2017-07-19 17:32
The underlying root cause is the use of GWT `Frame` objects to manage the popup of Java Quick documentation and Java completion documentation.
The Frame object creates an new html frame in which the client-side Keycloak-related Javascript code cannot be injected. And thus the http requests sent from these frames don't get the right Keycloak authorization token, and are refused on the server-side by the Keycloak Authentication filter.

FTR I created the following issue in upstream Che: https://github.com/eclipse/che/issues/5745

**Comment by davidfestal** [comment] 2017-07-20 12:12
This is fixed in production since version `1.0.234` of OSIO Che

**Closed by davidfestal** 2017-07-20 12:12 UTC
Labels: kind/bug, sprint/current-sprint
