### ISSUE TITLE
It should be possible to start Che workspace when namespace of type user is missing

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1042] opened 2018-11-03 19:23 UTC
**Issue problem:** 
On workspace provisioning step we get information about namepsace of type `user`. But if such namespace is missing user can't start any workspace.

**Comment by ibuziuk** [comment] 2019-03-26 16:39
@alexeykazakov this is the second iteration of https://github.com/redhat-developer/rh-che/issues/1296 
should we consider taking it to the next sprint?

**Comment by alexeykazakov** [comment] 2019-03-26 16:46
@ibuziuk IMO yes. But @gorkem can confirm if this is what we want (to be ready to drop usernamespaces the next sprint).

**Comment by ibuziuk** [comment] 2019-03-26 16:50
ok waiting for confirmation before adding to the pri doc for the next sprint

**Comment by ibuziuk** [comment] 2019-04-02 14:12
@alexeykazakov we are NOT planning to take this issue to the next sprint. If the issue should be tackled during the next sprint please comment

**Comment by amisevsk** [comment] 2019-04-04 19:05
FWIW it looks like a relatively simple issue to fix, so if it's pressing I wouldn't be against spending half a day working on it next sprint -- this wouldn't interfere with planning much. WDYT @ibuziuk ?

If it turns out to be more complicated than it looks, we can drop it from the sprint but if it can be fixed in a few hours I think we could include it.

**Comment by amisevsk** [comment] 2019-04-04 19:11
From what I can tell, what we're doing now is getting namespace, cluster URL, and certs from the user namespace and injecting them into the workspace (presumably so that `oc` commands in the workspace use the `user` namespace. Simply replacing the `user` namespace with `-che` would only change where `oc` commands are run. The caveat here is that whatever we do with `oc` would then have to fit in the `-che` namespace alongside the workspace, which could be a problem.

**Comment by ibuziuk** [comment] 2019-04-08 14:24
@amisevsk no, I suppose we should not work on until user workspace would be confirmed to be removed, once it is done we would simply do a cleanup including removal of `login to OSO` installer. At the moment we do not plan to add this issue to the next sprint, so no work is needed in this deirection cc: @alexeykazakov @gorkem

**Comment by ibuziuk** [comment] 2019-12-18 18:38
Going to close after the next production update

**Comment by ibuziuk** [comment] 2020-01-22 15:28
The fix is on prod. Closing

**Closed by ibuziuk** 2020-01-22 15:28 UTC
Labels: kind/bug, level/beginner
