### ISSUE TITLE
Theia fails to init on OpenShift.io Che - Theia image endpoint requires auth

### ISSUE THREAD

**Issue by sr229** [redhat-developer/rh-che#1096] opened 2018-11-25 13:51 UTC
**Issue problem:** 

RH Che fails to boot the Theia image because it lacks authentication.

**Red Hat Che version:**  6.13.1

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Simply make any project with Theia sidecar enabled.

You will recieve the following:
```

Starting plugins processing

Started Plugin Broker

List of plugins and editors to install
- che-machine-exec-plugin:0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- org.eclipse.che.editor.theia:1.0.0 - Eclipse Theia

All plugins have been successfully processed

Successfully assigned chinodesuuu-che/workspace2y1hqvdwy5g1f5zw.ws-7c99f79b5b-m6kdw to ip-172-31-69-6.us-east-2.compute.internal

pulling image "eclipse/che-jwtproxy:latest"

Successfully pulled image "eclipse/che-jwtproxy:latest"

Created container

pulling image "eclipse/che-dev:nightly"

Started container

Successfully pulled image "eclipse/che-dev:nightly"

Created container

Started container

pulling image "wsskeleton/che-machine-exec"

Successfully pulled image "wsskeleton/che-machine-exec"

Created container

Started container

pulling image "eclipse/che-theia:0.3.16-nightly"

Error: ErrImagePull

Failed to pull image "eclipse/che-theia:0.3.16-nightly": rpc error: code = Unknown desc = unauthorized: authentication required

Error: Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "eclipse/che-theia:0.3.16-nightly": rpc error: code = Unknown desc = unauthorized: authentication required', 'workspace2y1hqvdwy5g1f5zw.ws-7c99f79b5b-m6kdw'"

```

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by sr229** [comment] 2018-11-26 10:22
Confirming this is edge case, Theia seems to pull fine now. You guys probably need to triage this:

If this helps, this happened around Midnight in Japanese time (AFAIR it was 00:30-01:30)

**Comment by ibuziuk** [comment] 2018-11-26 11:36
@riuvshin any ideas about why `**rpc error: code = Unknown desc = unauthorized: authentication required'**` could have happen on one of the starter clusters?
@sr229 could you please provide your username on osio / che.openshift.io ?

**Comment by ibuziuk** [comment] 2018-11-26 11:42
currently image pulling seems to work just fine (at very least on `us-east-2` cluster )

**Comment by sr229** [comment] 2018-11-27 05:48
@ibuziuk it would be `chinodesuuu`. This happpened while I was deploying a Che 7 stack.

**Comment by ibuziuk** [comment] 2019-06-02 22:23
Closing as outdated. Feel free to reopen if the issue is still reproducible - we will contact SD / Sre

**Closed by ibuziuk** 2019-06-02 22:23 UTC
Labels: kind/bug, status/analyzing
