### ISSUE TITLE
Include oc command in all stacks used in openshift.io

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#292] opened 2017-08-24 15:05 UTC
Can be useful for the osio workshop so we won't need to download and run it locally.

Maybe also see how we could inject the user token and other preferences so we don't have to configure anything to oc jenkins or che, etc ...

**Comment by bmicklea** [comment] 2017-09-10 23:38
Is this in the current sprint?

**Comment by ibuziuk** [comment] 2017-09-11 08:05
@bmicklea I will provide PR today

**Comment by sunix** [comment] 2017-09-11 11:59
@ibuziuk could be something similar to https://github.com/sunix/docker-chedev/blob/centos/Dockerfile#L37

**Comment by ibuziuk** [comment] 2017-09-11 17:22
PR for vertx recipe has been sent - https://github.com/redhat-developer/che-dockerfiles/pull/20
once approved & merged I will provide PR for adding oc to other rhche recipes in one go

**Comment by ibuziuk** [comment] 2017-09-12 08:36
PR for including oc to the rest of the recipes - https://github.com/redhat-developer/che-dockerfiles/pull/21

**Comment by ibuziuk** [comment] 2017-09-13 00:10
All pre-difined stacks now include oc binaries. Closing

**Closed by ibuziuk** 2017-09-13 00:10 UTC
Labels: kind/enhancement, severity/P1

**Comment by gorkem** [comment] 2017-09-13 00:22
Isn't this going to create more issues than it resolves. Around mid November we will get oc is out-of-date issue reported, and when we add the next language/framework to OSIO, there will be the stack is missing oc issue. Do we at least have an issue somewhere to remind us for a long term solution?

**Comment by ibuziuk** [comment] 2017-09-13 07:31
> Around mid November we will get oc is out-of-date issue reported, and when we add the next language/framework to OSIO

Well, once oc is outdated we will need to update version in images[1] for now

> when we add the next language/framework to OSIO, there will be the stack is missing oc 

but isn't it the similar thing as we have with node & bayesian right now (if one want to have bayesian ls image must have node installed). So, node is installed pretty much in every single rhche image

> Do we at least have an issue somewhere to remind us for a long term solution?
@l0rd am I correct that we are going to have some base image for all rhche stacks with all osio required stuff installed (node, oc, etc.) ?

[1] https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/centos-nodejs/Dockerfile#L12

**Comment by l0rd** [comment] 2017-09-13 11:51
@ibuziuk that is not as simple. The problem is that we don't have multiple inheritance for dockerfiles (and osio vertx must inherit upstream vertx). But what we can do is that we can have a same shared script to add all Che dependencies.

To get latest stable oc we could use `curl -s https://api.github.com/repos/openshift/origin/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep client.*linux-64bit.tar.gz` but not sure that it would solve the problem.

**Comment by gorkem** [comment] 2017-09-13 15:04
@ibuziuk Yes, it is the same issue with node which is a pain. I wonder if we could avoid adding to that with an agent perhaps? Ideally I would like everything like oc/maven/node to be side-cars but we are not there yet
