### ISSUE TITLE
 Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate',

### ISSUE THREAD

**Issue by jfrantzius** [redhat-developer/rh-che#1731] opened 2019-12-11 10:40 UTC
**Issue problem:** 
Running my workspace fails as follows:

> Error:` Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspacemlr4cfc38hv11x6w.nodejs-6f4777955c-zm24j" is forbidden: [maximum cpu usage per Pod is 6, but limit is 7607m., maximum memory usage per Pod is 3Gi, but limit is 4085205504.]', 'workspacemlr4cfc38hv11x6w.nodejs-6f4777955c'"

**Red Hat Che version:** 

Dashboard says: Eclipse Che 7.3.2

 - [x ] I can reproduce it on latest official image
(created the workspace yesterday)

**Reproduction Steps:**

Perhaps the problem can be reproduced by using the same Devfile with a free account (only opensource projects used on Github):
```yaml
metadata:
  name: wksp-9x6d
projects:
  - name: jfrantzius-carbon-website
    source:
      location: 'https://github.com/jfrantzius/carbon-website.git'
      type: git
  - name: nodejs-web-app
    source:
      location: 'https://github.com/che-samples/web-nodejs-sample.git'
      type: git
attributes:
  persistVolumes: 'false'
components:
  - id: che-incubator/typescript/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 3000
    memoryLimit: 512Mi
    type: dockerimage
    alias: nodejs
    image: 'quay.io/eclipse/che-nodejs10-ubi:nightly'
  - id: sonarsource/sonarlint-vscode/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: redhat/vscode-camelk/latest
    type: chePlugin
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
apiVersion: 1.0.0
commands:
  - name: download dependencies
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/nodejs-web-app/app'
        type: exec
        command: npm install
        component: nodejs
  - name: run the web app
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/nodejs-web-app/app'
        type: exec
        command: nodemon app.js
        component: nodejs
  - name: run the web app (debugging enabled)
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/nodejs-web-app/app'
        type: exec
        command: nodemon --inspect app.js
        component: nodejs
  - name: stop the web app
    actions:
      - type: exec
        command: >-
          node_server_pids=$(pgrep -fx '.*nodemon (--inspect )?app.js' | tr
          "\\n" " ") && echo "Stopping node server with PIDs:
          ${node_server_pids}" &&  kill -15 ${node_server_pids} &>/dev/null &&
          echo 'Done.'
        component: nodejs
  - name: Attach remote debugger
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "type": "node",
                "request": "attach",
                "name": "Attach to Remote",
                "address": "localhost",
                "port": 9229,
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "${workspaceFolder}"
              }
            ]
          }
        type: vscode-launch
```

**Runtime:**
I don't know how to tell.

**Comment by amisevsk** [comment] 2019-12-11 16:52
> Error:` Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspacemlr4cfc38hv11x6w.nodejs-6f4777955c-zm24j" is forbidden: [maximum cpu usage per Pod is 6, but limit is 7607m., **maximum memory usage per Pod is 3Gi, but limit is 4085205504**.]', 'workspacemlr4cfc38hv11x6w.nodejs-6f4777955c'"

For now, che.openshift.io users are limited to a `3Gi` memory quota. The added plugins in your devfile result in a worksapce that requests `~3.8Gi`, and this is blocked by the cluster. The memory use for the plugins not listed is:

| plugin | memory limit |
| --- | --- |
| `sonarsource/sonarlint-vscode/latest` | `512Mi` | 
| `redhat/vscode-yaml/latest` | `256Mi` |
| `redhat/vscode-camelk/latest` | `1G` |
| `ms-vscode/node-debug2/latest/` | `512Mi` |

To workaround the failure, you can try to reduce these default requests by setting a memoryLimit in the devfile, as is done for the typescript plugin:
```yaml
  - id: che-incubator/typescript/latest
    memoryLimit: 512Mi
```
but this might be tricky.

I agree that the error message could be more meaningful, though.

**Comment by ibuziuk** [comment] 2019-12-11 19:39
@jfrantzius we are considering increasing RAM, but the current limit is 3GB - https://www.eclipse.org/che/docs/che-7/hosted-che/#terms-of-service_hosted-che

**Comment by ibuziuk** [comment] 2020-02-14 13:42
@jfrantzius RAM has been increased [1] to 7GB, could you please confirm that the issue is not reproducible anymore? 

[1] https://www.eclipse.org/che/docs/che-7/hosted-che/#terms-of-service_hosted-che

**Comment by ibuziuk** [comment] 2020-03-04 10:36
Closing. Feel free to reopen if still reproducible for you

**Closed by ibuziuk** 2020-03-04 10:36 UTC
Labels: kind/question
