### ISSUE TITLE
Che: Create Workspace, fails to Import

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#104] opened 2017-06-12 01:49 UTC
_From @burrsutter on June 9, 2017 17:2_

After running the Wizard for a new Vert.x basic project, I click Create Workspace and Che launches but often (perhaps always) it fails to load the project by default.

https://screencast.com/t/H3UgZn1qF

workaround is to manually import the project

_Copied from original issue: openshiftio/openshift.io#217_

**Comment by l0rd** [comment] 2017-06-16 13:50
@burrsutter I've being playing with osio the last couple of days but I could not reproduce this one.

That's annoying because it may be something that we have fixed lately but I honestly can't tell what. 

So let's keep this open for now. If you reproduce the problem again please make sure to provide some logs:

```bash
ID=<your osio id>
TOKEN=<your oso token>
oc login https://api.starter-us-east-2.openshift.com --token=${TOKEN}
oc project ${ID}-che

# get wsagent logs
WS_POD_ID=$(oc get pods -o=custom-columns=NAME:.metadata.name --no-headers | grep che-ws)
oc rsh ${WS_POD_ID} \
     sh -c "cat /home/user/che/ws-agent/logs/*/*/*/catalina-0.log"

# get bayesian logs
oc rsh ${WS_POD_ID} \
     sh -c "cat /projects/bayesian.log" # bayesian.log will move to /home/user/che/ls-bayesian

# get wsmaster logs
MASTER_POD_ID=$(oc get pods -o=custom-columns=NAME:.metadata.name --no-headers | grep che-[0-9])
oc logs ${MASTER_POD_ID}
```
Probably this info should be in a wiki or FAQ but I don't know if it makes sense [here](https://github.com/openshiftio/openshift.io/wiki/FAQ)?

**Comment by joshuawilson** [comment] 2017-06-16 14:48
@l0rd I think adding that to the wiki makes a lot of sense. That is the most public repo we have and we will direct users to that wiki. Can you please this to the FAQ?

**Comment by l0rd** [comment] 2017-06-16 17:55
@joshuawilson when you talk about the wiki you mean this github repo wiki or openshift.io wiki?

**Comment by joshuawilson** [comment] 2017-06-16 18:19
@l0rd I mean adding it to the [FAQ](https://github.com/openshiftio/openshift.io/wiki/FAQ)

**Comment by pkettman** [comment] 2017-06-21 08:57
I experienced similar behavior: workspace 'mcx9upqk' was created, related project was not imported and in addition:
1) following exception was thrown in Che log: https://gist.github.com/pkettman/48042894a32f2e38b6e4219bd7516855 and
2) the workspace is not visible/accessible from OSIO Codebases page

**Comment by ibuziuk** [comment] 2017-07-18 16:53
should be fixed now, since `openshift-connector-rebased` was pushed to master. Feel free to reopen

**Closed by ibuziuk** 2017-07-18 16:53 UTC
Labels: kind/question, status/analyzing
