### ISSUE TITLE
[Che issue] Workspace reloaded twice during workspace readyness test

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1837] opened 2020-03-19 12:15 UTC
The welcome page was opened multiple times, tests stuck on readme file

![image](https://user-images.githubusercontent.com/16451875/77066593-bc8be980-69e3-11ea-8677-b18263f8e2b1.png)
![image](https://user-images.githubusercontent.com/16451875/77066601-beee4380-69e3-11ea-88d8-951cbf0333f7.png)

**Comment by ScrewTSW** [comment] 2020-03-19 12:16
Seen during the weekend on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2277/console

**Comment by ScrewTSW** [comment] 2020-03-19 12:16
Seen today again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2298/console

**Comment by ScrewTSW** [comment] 2020-03-20 08:06
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2302/console

**Comment by Katka92** [comment] 2020-03-23 10:21
Seen again on production 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2314/console
Workspace was reloaded 3 times on prod-preview cluster 2a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2518/console

This issue is weird, workspace stays long in this state [1] and then it started to be loaded correctly, but test stops to wait and refresh. I'm not sure if this is a good way to go. We should reconsider this behavior.

[1]
![image](https://user-images.githubusercontent.com/29278800/77305850-07b13f80-6cf7-11ea-82fb-a19c006de32b.png)

**Comment by Katka92** [comment] 2020-03-24 07:13
Seen on cluster 1a 2x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2324/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/2325/console

**Comment by ScrewTSW** [comment] 2020-03-31 07:29
Seen again on production cluster 1a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2368/console

**Comment by ScrewTSW** [comment] 2020-04-01 11:26
Seen again on prod-preview cluster 2a x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2585/console

**Comment by ScrewTSW** [comment] 2020-04-02 12:33
Seen again on production cluster 1a x3:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2377/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/2378/consoleFull - x2

**Comment by Katka92** [comment] 2020-04-06 09:28
Seen again on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2600/console

**Comment by ScrewTSW** [comment] 2020-04-27 13:05
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2736/console

**Comment by ScrewTSW** [comment] 2020-04-28 08:31
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2748/console

**Comment by Katka92** [comment] 2020-05-04 09:45
As we have a video from tests now, I found out that if the workspace switch to offline (e.g. during a command run as in a video [1]), when it loads again, the second `Eclipse Che` page is opened. To see what happened, see the video at 1:30. 

Related issue https://github.com/redhat-developer/rh-che/issues/1633

[1] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/2774/e2e_report/report/ffmpeg_report/output.mp4

Seen on cluster 2 1x
Seen on prod-preview 2x too
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2778/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2779/console

**Comment by ScrewTSW** [comment] 2020-05-11 12:58
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2811/console

**Comment by ScrewTSW** [comment] 2020-05-14 13:04
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2843/console

**Comment by Katka92** [comment] 2020-05-18 06:44
Closing in favor of #1848 as this issue describes the root cause.

**Comment by ScrewTSW** [comment] 2020-05-26 07:26
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2912/console

**Comment by Katka92** [comment] 2020-06-02 13:01
Closing in favor of #1848 as this issue describes the root cause.

**Comment by ScrewTSW** [comment] 2020-06-12 09:43
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3016/console

**Closed** 2020-06-23 12:34 UTC
Labels: kind/periodic-e2e-test, team/rhche-qe
