### ISSUE TITLE
Recommendations on pom.xml are currently not working

### ISSUE THREAD

**Issue by mlabuda** [redhat-developer/rh-che#218] opened 2017-07-20 12:36 UTC
I have a Che server running on image rhche/che-server:ba40d4c-fabric8-5bd0962 (15 hours old) and template 1.0.231. There is a env var RECOMMENDER_API_TOKEN, also there is com.redhat.bayesian.lsp agent present in workspace but there is no server.js running in workspace nor working Bayesian. Che server in log contains info about launching bayesian LSP
`2017-07-20 09:10:38,699[aceSharedPool-4] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692] - Launching 'com.redhat.bayesian.lsp' agent at workspace workspacex66f4i8nrf48xrqq`

**Comment by l0rd** [comment] 2017-07-20 15:30
@mlabuda I've changed the title of this issue because it looks like the issue is only for recommendation with `pom.xml` files. You can find more details below: 

**WHEN IS BAYESIAN NODE APP STARTED?** 
Bayesian node app is started only when a file (`package.json`, `pom.xml` or `requirement.txt`) is opened. That explains why you don't see the application after workspace startup. You need to open one of these files first.

**ISSUE WITH pom.xml files**
Currently recommendation agent is not activated for `pom.xml` files. That's is a side effect of the rebase we did last week on top of last version of `eclipse/che` that didn't support multiple LS on a single file. That problem has been solved and merged on `eclipse/che` and will be fixed on `rhche` with #200  

Said that Bayesian LS is working fine on OSIO for a `package.json` file:

![image](https://user-images.githubusercontent.com/606959/28425329-3df54e62-6d70-11e7-9c86-6a208a667a89.png)

cc @invincibleJai @samuzzal-choudhury

**Comment by invincibleJai** [comment] 2017-07-20 16:14
thanks @l0rd @mlabuda for putting more light on it. I tested requirements.txt as well , it's working as expected.

**Comment by krishnapaparaju** [comment] 2017-07-20 17:04
@l0rd  @invincibleJai  thanks

**Comment by davidfestal** [comment] 2017-07-24 13:39
Created PR https://github.com/redhat-developer/rh-che/pull/223. let's wait for the merge and promotion to prod before closing the issue.

**Comment by invincibleJai** [comment] 2017-07-26 05:37
@davidfestal Thanks, now bayesian LSP is working with CHE for pom.xml tested in osio
(with Image: rhche/che-server:8c76cd6-fabric8-4d2c60e) 

However one observation is earlier we need to edit once to see CVE's flagging on pom.xml. Issue for same ( https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/issues/13 ),
now i observed needed to edit more than once(there are some flickering notifications as well like "loading content"). This behaviour is only there for pom.xml and not for package.json or requirements.txt. I'll be looking into this , do let me know if you have any idea about this.

<img width="1676" alt="screen shot 2017-07-25 at 2 14 25 pm" src="https://user-images.githubusercontent.com/5129024/28606003-71d803d8-71f2-11e7-880a-e9ad0e6d5119.png">

cc @samuzzal-choudhury

**Comment by davidfestal** [comment] 2017-07-26 07:45
> do let me know if you have any idea about this

I don't have any idea for now on this one. Maybe @tsmaeder might have some idea: he worked on multi-LS support.

However don't you think we should open a new issue for this other problem, and close this one ?

**Comment by l0rd** [comment] 2017-07-26 08:05
This seams still related to #101 and may be fixed in bayesian LS (https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/issues/13). @tsmaeder @msrb can you please confirm?

**Comment by invincibleJai** [comment] 2017-07-26 08:19
@davidfestal sure we can close this one. @l0rd it's not fixed in bayesian LS , i'll look into this and update as i was unable to see this behaviour on local minishift instance earlier will take latest and check.

**Comment by l0rd** [comment] 2017-07-26 11:13
@davidfestal @invincibleJai Let's keep this open until fabric8-analytics/fabric8-analytics-lsp-server#13 is fixed and we have verified that pom.xml recommendations work fine.

**Comment by l0rd** [comment] 2017-08-04 15:30
Closing this one since it's fixed Che side.

**Closed** 2017-08-04 16:47 UTC
Labels: kind/bug, sprint/current-sprint
