### ISSUE TITLE
Apache Camel example not working on production

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1615] opened 2019-09-13 10:30 UTC
**Issue problem:** 
When running `Apache Camel based on Spring Boot` on production, the workspace can not start. This issue is not reproducible on prod-preview. Devfiles are same on production and prod-preview.

![Screenshot from 2019-09-13 12-21-44](https://user-images.githubusercontent.com/29278800/64855872-1a004180-d621-11e9-9ccf-713c7170c75d.png)

**Red Hat Che version:** 

version: 7.1.0

**Reproduction Steps:**
Create a default Apache Camel workspace with default settings and with example project. 

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment] 2019-09-18 07:19
@Katka92 could you please add namespaces example where the same devfile works and where it is not, since this looks like admission controller setup issue: 

> Pod "workspacezech2cscku1nu8nb.maven-bd4d75d56-v2l5s" is invalid: spec.containers[3].resources.requests:
>       Invalid value: "150Mi": must be less than or equal to memory limit

**Comment by Katka92** [comment] 2019-09-18 08:07
@ibuziuk Sure :) 
Fails on `kkanova` cluster 2 and `osio-ci-e2e-004` cluster 1b
Succeeds for `osiotest2` on cluster 2 and `osiotest-workspace-1b` on cluster 1b

**Comment by RickJWagner** [comment] 2019-09-23 12:55
I can replicate this on che.openshift.io, asking for a Camel/SpringBoot application.

**Comment by l0rd** [comment] 2019-09-23 13:07
On osio containers cannot have memory limit < 150MB. For instance [that doesn't work](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/apache-camel-springboot/devfile.yaml#L15).

**Comment by ibuziuk** [comment] 2019-09-23 13:25
@l0rd the funny thingy that this works in some namespaces 
@pbergene @jfchevrette looks like that some of the admission controllers are not applied across all the *-namespaces

**Comment by amisevsk** [comment] 2019-09-24 02:15
FWIW from some discussion earlier, it seems that not all namespaces have the same minimum memory limit. Some have a minimum of `32Mi`, others have `150Mi`. 

The error message is deceptive, since I think there's an admission controller that rewrites requests to be the minimum, which causes the issue shown. See https://coreos.slack.com/archives/CCRND57FW/p1568383360487000 for details.

**Comment by l0rd** [comment] 2019-09-24 07:23
Anyway the "easy fix" here is to change the limit to `150MB` in the camel devfile. And since we should rollout the 7.2 release soon we may have that in prod by the end of the week.

**Comment by ibuziuk** [comment] 2019-09-24 10:42
hmm... today the Apache Camel worked for me @Katka92 can you reproduce with the `kkanova` against cluster 2 ?

**Comment by Katka92** [comment] 2019-09-24 10:53
For user `kkanova` still failing. You can see oc events here: https://gist.github.com/Katka92/8f4268790766e3680bc8c4369741812f

**Comment by ibuziuk** [comment] 2019-09-24 11:16
The root cause is that https://github.com/fabric8-services/fabric8-tenant/pull/727 was not applied for all namespaces and we do need to proceed with global tenant-update in order to apply the same quotas. For some reason the quotas were applied not to all namespaces for example:

- `ibuziuk-che` (us-east-2) - Limit is 30Mi

![image](https://user-images.githubusercontent.com/1461122/65506812-c0bfca00-decc-11e9-8109-8aa9da755b91.png)

- kkanova-che (us-east-2) - Limit is 150Mi
![image](https://user-images.githubusercontent.com/1461122/65506869-e64cd380-decc-11e9-936a-556abb93b737.png)


@alexeykazakov how could we request a cluster wide tenant update in order to apply the same quotas for all namespaces? Looks like the config is different for different namespaces 

In the meantime, I will provide a PR with a workaround on devfile end

**Comment by ibuziuk** [comment] 2019-09-24 11:37
PR with a workaround - https://github.com/eclipse/che-devfile-registry/pull/101
@Katka92 could you please try it on Hosted Che with `kkanova` account and provide your approval ?

**Comment by alexeykazakov** [comment] 2019-09-24 21:23
> @alexeykazakov how could we request a cluster wide tenant update in order to apply the same quotas for all namespaces? Looks like the config is different for different namespaces

It would be best if you create a JIRA for that in https://jira.coreos.com/browse/CRT
cc: @MatousJobanek

**Comment by ibuziuk** [comment] 2019-09-25 07:43
@alexeykazakov @MatousJobanek issue created - https://jira.coreos.com/browse/CRT-270
Current rh-che issue is going to be closed once Hosted Che is updated to the latest `7.2.0` release

**Comment by alexeykazakov** [comment] 2019-09-25 15:48
> Current rh-che issue is going to be closed once Hosted Che is updated to the latest 7.2.0 release

When is it going to happen?

**Comment by ibuziuk** [comment] 2019-09-25 15:50
@alexeykazakov early October, but we already applied workaround on devfile end

**Comment by MatousJobanek** [comment] 2019-10-10 12:19
@ibuziuk @Katka92  The cluster-wide update should be finished, could you please check that everything is set correctly now?

**Comment by Katka92** [comment] 2019-10-11 05:55
@MatousJobanek Seem like the quota was changed on my account `kkanova` [1] and I was able to start Apache Camel workspace correctly. The same for `osio-ci-e2e-004`.

[1]
![Screenshot from 2019-10-11 07-48-27](https://user-images.githubusercontent.com/29278800/66627316-8f007000-ebfb-11e9-8347-89d7ae4e6aaf.png)

**Comment by ibuziuk** [comment] 2019-10-14 09:38
@MatousJobanek great job. Closing

**Closed by ibuziuk** 2019-10-14 09:38 UTC
Labels: kind/bug, severity/P1
