### ISSUE TITLE
Fix workspace startup tests

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1736] opened 2019-12-18 09:14 UTC
**Description:**
Workspace startup tests are broken and no report is sent to slack for some time. The problem was that the jobs were stuck in a long queue on a Jenkins. As a solution those jobs and a job that is reporting results to slack were disabled.

**Comment by ScrewTSW** [comment] 2020-01-27 10:25
![Screenshot_20200127_111259](https://user-images.githubusercontent.com/16451875/73166946-2f20cd00-40f7-11ea-8b8e-1db6d06c3b15.png)
![Screenshot_20200127_111154](https://user-images.githubusercontent.com/16451875/73166947-2f20cd00-40f7-11ea-94df-5b8a8bf9627f.png)

The problem is with OpenStack. Job runs take up to maximum of 3 minutes and are executed every 30 minutes.

For some reason provisioning of the workers was taking 30+ minutes and caused the job queue to stack up.

**Comment by Katka92** [comment] 2020-01-27 10:42
@ScrewTSW Thanks for the investigation. So what would be the solution? What about increasing the period to run tests every hour instead of 30 minutes?

**Comment by ScrewTSW** [comment] 2020-02-27 08:55
It seems that the problem has mostly fixed itself. Closing.

**Closed by ScrewTSW** 2020-02-27 08:55 UTC
Labels: kind/task, team/rhche-qe
