### ISSUE TITLE
Bayesian lsp not working correctly on mt che on prod-preview

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#455] opened 2017-11-23 12:38 UTC
**Issue problem:** 
https://github.com/redhat-developer/che-functional-tests/blob/master/tests/src/test/java/redhat/che/functional/tests/PomTestCase.java is failing against mt che on prod preview (using account kkanova-osiotest1).

What is this test doing?
1) It creates workspace (using che-starter) with vert.x stack and vertx-http-booster project.
2) Opens pom.xml of the project and writes this dependency into dependencies section:
```
<dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-core</artifactId>
        <version>1.1.10</version>
</dependency>
```
3) Bayesian LSP should mark this dependency as errorneous (it contains some CVE), but this step fails on mt che on prod-preview.

I was able to reproduce this even by hand.
I wasn't able to reproduce this on prod (single tenant nor multi tenant). (Which is weird, because che version on both prod and prod-preview seems to be the same)
I haven't tried that on prod-preview with single tenant che.

**Red Hat Che version:** 

Version :1.0.0-SNAPSHOT
Revision :c27e4061bd96d868
Build Time :2017-11-17 13:05:25

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io (prod preview)
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

I can see nothing weird in logs. Doing `ps -aux |grep baye` in che workspace terminal prints few bayesian processes, so it seems, that bayesian LSP is running.

**Comment by ibuziuk** [comment] 2017-11-23 12:45
"now" or "not" ?

**Comment by ibuziuk** [comment] 2017-11-23 12:48
Also, could you please verify that the problem is fixed on master - https://github.com/redhat-developer/rh-che/issues/367 ?

**Comment by rhopp** [comment] 2017-11-23 16:04
You are correct. "Not" is the right word. Don't know how I could have typed "w" instead of "t". Title fixed.

**Comment by ibuziuk** [comment] 2018-06-07 11:08
Closing as a duplicate of https://github.com/redhat-developer/rh-che/issues/524

**Closed by ibuziuk** 2018-06-07 11:08 UTC
Labels: kind/bug, severity/low-priority
