### ISSUE TITLE
Che: loading of the pom.xml

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#102] opened 2017-06-12 01:47 UTC
_From @burrsutter on June 9, 2017 13:23_

Two things: 
1) the pom.xml auto-closes in Che, if I leave the browser tab for too long or after having put the laptop to sleep, or perhaps it is my tab suspender, I find the pom.xml has closed
2) opening the pom.xml may say "loading language server protocol" or something like that and essentially stay frozen, the solution is to stop and start the workspace from the Dashboard.

_Copied from original issue: openshiftio/openshift.io#211_

**Comment by tsmaeder** [comment] 2017-07-17 15:35
I don't really know how to reproduce this. Opening/Closing pom.xml files works for me. Doing a file refresh works. 
The version of Che deployed on OSIO at the time of this happening would block eternally whenever an error occurred when starting a language server. So all we know right now is "something went wrong".
Later versions of Che have both proper error handling and timeout, so we should get some error info when this happens. Do we have recent occurrences of this problem?

**Comment by tisnik** [comment] 2017-07-18 12:42
I've seen similar issue in Firefox 51.0.1 w/o any plugins. The timeout is quite high (>15 minutes). I'll add more information how to reproduce this issue later.

**Comment by l0rd** [comment] 2017-07-18 14:44
@tisnik can you tell us what version of Che you are using?

**Comment by tisnik** [comment] 2017-07-18 15:07
@l0rd it is on production,
Revision : 76f86431c6f647c5
Build Time : 2017-07-07 18:10:49

For the record it happened only once on my side, so I'm going to leave the browser in idle state for a much longer time (say one hour or so)

**Comment by l0rd** [comment] 2017-07-18 15:24
@tisnik thanks. Your Che version on prod may be different from mine (because che-server update on openshift.io is done manually). 

Can you please look at the version from openshift.io UI:
![image](https://user-images.githubusercontent.com/606959/28324991-0d24108c-6bdd-11e7-99f1-e4e99aa741b9.png)

**Comment by l0rd** [comment] 2017-07-18 15:27
@tisnik [faq on how to update Che to latest version]( https://github.com/openshiftio/openshift.io/wiki/FAQ#how-do-i-update-my-tenant-)

**Comment by tisnik** [comment] 2017-07-18 16:09
@l0rd it is 1.0.205 on mi side. So I suppose I'd need to update, right?

**Comment by joshuawilson** [comment] 2017-07-18 19:18
yes, you can update from the user profile

**Comment by l0rd** [comment] 2017-07-19 09:18
Yes @tisnik please update Che. If the problem still persist provide the steps needed to reproduce it.

**Comment by tisnik** [comment] 2017-07-19 11:50
@l0rd I'm unable to reproduce the issue after updating Che to the version 1.0.220

**Comment by l0rd** [comment] 2017-07-19 12:10
Thank you @tisnik for your help. Che version 1.0.208 brought some main changes to the LS support that should have fix that. I'm closing this issue.

**Closed by l0rd** 2017-07-19 12:10 UTC
Labels: kind/bug, sprint/next-sprint, status/analyzing
