### ISSUE TITLE
Unable to start a workspace from a factory url

### ISSUE THREAD

**Issue by benoitf** [redhat-developer/rh-che#839] opened 2018-08-30 08:39 UTC
**Issue problem:** 
Che allows to use factory URLs like `https://che.openshift.io/f?url=<url-of-a-github-repository>`

When using that mode, workspace fails to start.

<details><summary>Details of stack trace</summary><p>

147 lines are hidden...

at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
Caused by: org.eclipse.che.api.core.NotFoundException: Factory with id 'undefined' doesn't exist
at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:269)
at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.(AnalyticsManager.java:121)
at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.class(AnalyticsManager.java:72)
at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.(AnalyticsManager.java:193)
2) Error injecting constructor, java.lang.RuntimeException: Can't get workspace informations for Che analytics
at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:163)
at java.lang.Thread.run(Thread.java:748)
while locating com.redhat.che.plugin.analytics.wsagent.AnalyticsManager
Caused by: java.lang.RuntimeException: Can't get workspace informations for Che analytics
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
at com.google.inject.Guice.createInjector(Guice.java:99)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.request(DefaultHttpJsonRequest.java:163)
at java.lang.Thread.run(Thread.java:748)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.(AnalyticsManager.java:183)
... 33 more
at org.eclipse.che.api.core.rest.DefaultHttpJsonRequest.doRequest(DefaultHttpJsonRequest.java:269)
2 errors
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
at com.google.inject.Guice.createInjector(Guice.java:99)
at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
at org.everrest.guice.servlet.EverrestGuiceContextListener.contextInitialized(EverrestGuiceContextListener.java:85)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
2018-08-30 08:19:44,783[ost-startStop-1] [ERROR] [o.a.c.core.StandardContext 5259] - Context [] startup failed due to previous errors
at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager$$FastClassByGuice$$30cb3d0a.newInstance()
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
... 43 more

at com.redhat.che.plugin.analytics.wsagent.AnalyticsManager.(AnalyticsManager.java:183)
2018-08-30 08:19:44,779[ost-startStop-1] [ERROR] [o.a.c.core.StandardContext 5208] - One or more listeners failed to start. Full details will be found in the appropriate container log file
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.lang.Thread.run(Thread.java:748)

at org.everrest.guice.servlet.EverrestGuiceContextListener.getInjector(EverrestGuiceContextListener.java:140)
at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47)
Caused by: org.eclipse.che.api.core.NotFoundException: Factory with id 'undefined' doesn't exist
at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
2018-08-30 08:19:44,815[ost-startStop-1] [INFO] [o.a.c.startup.HostConfig 1023] - Deployment of web application archive [/home/user/che/ws-agent/webapps/ROOT.war] has finished in [5,459] ms
2018-08-30 08:19:44,827[main] [INFO] [o.a.c.http11.Http11NioProtocol 632] - Starting ProtocolHandler ["http-nio-4401"]
2018-08-30 08:19:44,838[main] [INFO] [o.a.catalina.startup.Catalina 683] - Server startup in 5683 ms
2018-08-30 08:20:14,065[ted-scheduler-3] [ERROR] [o.e.c.c.s.e.LoggedRunnable 65] - null
2018-08-30 08:20:44,064[ted-scheduler-6] [ERROR] [o.e.c.c.s.e.LoggedRunnable 65] - null

</p></details>

**Red Hat Che version:** 

version: latest

 - [X] I can reproduce it on latest official image

**Reproduction Steps:**

click on https://che.openshift.io/f?url=https://github.com/che-samples/che-ide-extension

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by davidfestal** [comment] 2018-08-30 08:40
Great, Thanks !

**Comment by rhopp** [comment] 2018-08-30 11:17
This is reproducible also on prod-preview (che 6.10)

**Comment by davidfestal** [comment] 2018-09-12 11:34
worked on it in the context of issue https://github.com/redhat-developer/rh-che/issues/815

**Comment by benoitf** [comment] 2018-10-15 13:32
hello, it seems it is failing again (reopening)

**Comment by benoitf** [comment] 2018-10-15 13:33
@davidfestal it seems I'm redirected to dashboard

**Comment by sbose78** [comment] 2018-10-16 08:31
@davidfestal , the server doesn't receive the fragment from the URL at all - and that's as per spec.

"The fragment identifier functions differently to the rest of the URI: its processing is exclusively client-side with no participation from the web server, though the server typically helps to determine the MIME type, and the MIME type determines the processing of fragments. When an agent (such as a Web browser) requests a web resource from a Web server, the agent sends the URI to the server, but does not send the fragment."

**Comment by sbose78** [comment] 2018-10-16 08:32
Ref:

https://en.wikipedia.org/wiki/Fragment_identifier
https://github.com/golang/go/issues/3805#issuecomment-66068331
https://stackoverflow.com/a/25489996/823386

**Comment by sbose78** [comment] 2018-10-16 16:49
The fix has been merged. I need a confirmation that it works on prod-preview - before I move the change to production. https://github.com/fabric8-services/fabric8-auth/pull/696

**Comment by davidfestal** [comment] 2018-10-16 17:01
It seems to work perfectly on prod-preview.

**Comment by davidfestal** [comment] 2018-10-16 19:15
well, let me mention that is seems there some problem with how query parameters (if any) are managed:

If I pass this URL to the autorization endpoint:
```
https://auth.prod-preview.openshift.io/api/authorize?client_id=740650a2-9c44-4db5-b067-a3d1b2cd2d01&redirect_uri=https%3A%2F%2Fche.prod-preview.openshift.io%2Fdashboard%2F%3Ftest&state=980fe64f-e70f-47c1-8001-58fcd88a3931&response_mode=fragment&response_type=code&scope=openid
```
which corresponds to the following redirect_uri: `https://che.prod-preview.openshift.io/dashboard/?test`
then the browser is finally redirected to:
```
https://che.prod-preview.openshift.io/dashboard/?test#code=uss.1XtpVE-_gD4ARTs2TaaUFnzqo6EfLDH5TmmUi4AtMH8.0b7fc236-5098-46bd-89d9-47824df8e2a3.98447a27-40de-450b-a987-1ddc97730839&state=980fe64f-e70f-47c1-8001-58fcd88a3931&test=
```
which means that the `test` query parameter is duplicated as a fragment parameter at the end of the URL fragment: `&test=`
so that, once the OIDC fragment elements will be removed, we will have
```
https://che.prod-preview.openshift.io/dashboard/?test#test=
```
which is obviously not the same URL as the initially requested `redirect_uri`

it seems to me that only **new OIDC params + old fragment params** should be added as fragment params in the final URL but I don't see why we would like to transform old query params to new fragment params while letting them be there as query params at the same time (=> duplicate them finally)

**Comment by sbose78** [comment] 2018-10-16 19:55
note: this is an existing behaviour and not introduced by this change.

@davidfestal , 
1. Does this behaviour impact Che rendering?
2. Do you want to keep old params as is, and add new fragments only?

**Comment by benoitf** [comment] 2018-10-18 15:40
FYI it doesn't work as well for me for any factories. (id=something) as well.

**Comment by benoitf** [comment] 2018-10-18 15:42
so all links of https://www.eclipse.org/che/getting-started/cloud/ are not working on my side

**Comment by davidfestal** [comment] 2018-10-18 15:42
@benoitf That's expected, but should be fixed by the auth PR that is available since several days but cannot be deployed  because of failing end2end tests.

**Comment by ibuziuk** [comment] 2018-10-23 14:07
I tested on prod and workspace creation via factory link seems to be working just fine. Closing

**Closed by ibuziuk** 2018-10-23 14:07 UTC
Labels: kind/bug
