### ISSUE TITLE
[Che issue] Language server not working

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1565] opened 2019-08-16 05:29 UTC
Periodic tests on prod-preview and PR checks are failing on Language Server. I tried that manually and didn't work for me.
Problems:
- language server suggestions are not opened
- error is not highlighted
- autocomplete doesn't works as expected
- codenavigation doesn't work - e.g. I could not do `Ctrl + click` on a class

![Screenshot from 2019-08-16 07-22-22.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/26a81c78-cf71-498f-a414-ede1bb319c32)

**Screens for each desribed error:**
Suggestion invoking
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/ad380867-5624-4b15-92aa-12d349789ce8)

Error highlighting:
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/2bd63d1a-eec2-42fa-bd05-9e7f4c86be5c)

Autocomplete:
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/d6b68440-bce0-407b-97d0-c6d004284349)

Code navigation:
![image.png](https://images.zenhubusercontent.com/59a50d048f62dc7798c4656a/7627538c-dc0f-4258-a6da-431a19fcb2d0)

**Comment by rhopp** [comment] 2019-08-16 08:42
From what I can tell, the container was not restarted:
```
    - containerID: >-
        docker://f83b87d6dc8b244056ccbf0d671283575d00853bf6e1032eee24d8c9900bf365
      image: 'docker.io/eclipse/che-remote-plugin-runner-java8:next'
      imageID: >-
        docker-pullable://docker.io/eclipse/che-remote-plugin-runner-java8@sha256:15c0715b7d5e0e86c993823956f4ab18bf98d0abcd07d8aeab0be2db2b414ca4
      lastState: {}
      name: vscode-java6r7
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: '2019-08-16T08:24:16Z'
```
language server is not running in vscode-java container:
```
$ oc exec workspace2d8urabanlt8b530.maven-5b6cccd6fd-lsrl9 -c vscode-java6r7 ps aux                                                                                                                           1 ↵
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   1584   528 ?        Ss   08:24   0:00 /bin/sh /entrypoint.sh
root        20  0.3  0.1 335552 63960 ?        Sl   08:24   0:03 node /home/theia/lib/node/plugin-remote.js
root        47  0.0  0.0   1592   520 ?        Ss+  08:25   0:00 /bin/sh
root        56  0.0  0.0   1592   516 ?        Ss+  08:39   0:00 /bin/sh
root        64  0.0  0.0   1612   516 ?        Rs   08:41   0:00 ps aux
```
Here are logs of vscode-java container:
```
$ oc logs workspace2d8urabanlt8b530.maven-5b6cccd6fd-lsrl9 -c vscode-java6r7       
Starting the deployer with the list of resolvers [ LocalDirectoryPluginDeployerResolver {},
  GithubPluginDeployerResolver { unpackedFolder: '/tmp/github-remote' },
  HttpPluginDeployerResolver { unpackedFolder: '/tmp/http-remote' },
  VsCodePluginDeployerResolver { vscodeExtensionsFolder: '/tmp/vscode-extension-marketplace' } ]
Theia Endpoint 20/pid listening on port 2503
Found the list of default plugins ID on env: undefined
Found the list of plugins ID on env: local-dir:///plugins/sidecars/redhat_java_0_45_0
Found the list of default plugins ID from CLI: undefined
unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler { unpackedFolder: '/tmp/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:///plugins/sidecars/redhat_java_0_45_0',
     pluginId: 'redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      '/plugins/sidecars/redhat_java_0_45_0/redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix',
     initPath:
      '/plugins/sidecars/redhat_java_0_45_0/redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler { unpackedFolder: '/tmp/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:///plugins/sidecars/redhat_java_0_45_0',
     pluginId:
      'redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      '/plugins/sidecars/redhat_java_0_45_0/redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix',
     initPath:
      '/plugins/sidecars/redhat_java_0_45_0/redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix
Resolving "redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix" as a VS Code extension...
Resolved "redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix" to a VS Code extension "java@0.45.0" with engines: { vscode: '^1.31.0' }
PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix
Resolving "redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix" as a VS Code extension...
Resolved "redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix" to a VS Code extension "vscode-java-debug@0.16.0" with engines: { vscode: '^1.22.0' }
the accepted plugins are []
the acceptedFrontendPlugins plugins are []
the acceptedBackendPlugins plugins are [ PluginDeployerEntryImpl {
    originId: 'local-dir:///plugins/sidecars/redhat_java_0_45_0',
    pluginId: 'redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix',
    map: Map { 'package.json' => [Object] },
    changes:
     [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
    acceptedTypes: [ 1 ],
    currentPath:
     '/tmp/vscode-unpacked/redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix/extension',
    initPath:
     '/plugins/sidecars/redhat_java_0_45_0/redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix',
    resolved: true,
    resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  PluginDeployerEntryImpl {
    originId: 'local-dir:///plugins/sidecars/redhat_java_0_45_0',
    pluginId:
     'redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix',
    map: Map { 'package.json' => [Object] },
    changes:
     [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
    acceptedTypes: [ 1 ],
    currentPath:
     '/tmp/vscode-unpacked/redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix/extension',
    initPath:
     '/plugins/sidecars/redhat_java_0_45_0/redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix',
    resolved: true,
    resolvedByName: 'LocalDirectoryPluginDeployerResolver' } ]
local path to deploy on remote instance [ '/tmp/vscode-unpacked/redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix/extension',
  '/tmp/vscode-unpacked/redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix/extension' ]
Backend plug-in "java@0.45.0" from "/tmp/vscode-unpacked/redhat.java.0.45.0.cytiteiioo.java-0.45.0-1523.vsix/extension/dist/extension is now available"
Backend plug-in "vscode-java-debug@0.16.0" from "/tmp/vscode-unpacked/redhat.java.0.45.0.xzrkzxligb.vscode-java-debug-0.16.0.vsix/extension/out/src/extension is now available"
PLUGIN_HOST(20): PluginManagerExtImpl/init()
PLUGIN_HOST(20): initializing(java@0.45.0 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
PLUGIN_HOST(20): initializing(vscode-java-debug@0.16.0 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
Debugger contribution has been registered: java
```

**Comment by tsmaeder** [comment] 2019-08-16 10:00
This looks like it has nothing to do with the language server per se: it looks more like the vscode extensions is not properly working, in particular:

1. There are no "Java" commands in the command palette.
2. Changing the "java.jdt.ls.vmargs" preference should normally make the vscode-java extension offer to restart the language server, but doesn't.

However, the package.json seems to be read alright, because the preference contributions show up alright.

**Comment by tsmaeder** [comment] 2019-08-16 10:08
I'm seeing the same behaviour with a python workspace. I suspect this is a general problem with running remote plugins. @benoitf @evidolob could this have to do with plugin autodiscovery and a different networking environment?

**Comment by ibuziuk** [comment] 2019-08-19 06:41
I believe this started to happen after the update of the plugin registry in master - https://github.com/eclipse/che-plugin-registry/commit/191df1e76efdc1db993947d66a23f8aaff8b5eec

**Comment by tsmaeder** [comment] 2019-08-19 08:43
@ibuziuk 7.0.0-next and next of what?

**Comment by ibuziuk** [comment] 2019-08-19 09:26
@tsmaeder of the plugins - https://github.com/eclipse/che-plugin-registry/commit/191df1e76efdc1db993947d66a23f8aaff8b5eec

**Comment by vparfonov** [comment] 2019-08-19 09:31
Actually, i can't understand how it related https://github.com/eclipse/che/pull/14278

**Comment by ibuziuk** [comment] 2019-08-19 09:35
@vparfono could you clarify what is the difference between `7.0.0-next` to `next` che.openshift.io CI tests used to work just fine before the plugin version update and I do suspect this is the culprit.

**Comment by tsmaeder** [comment] 2019-08-19 09:35
Well, one thing that is strange in that PR is that the plugin runner images switches to "next" (I assume master) while the main theia container only has versions based on "7.0.0".

**Comment by vparfonov** [comment] 2019-08-19 09:41
We can switch to the Che Theia next until not fixed https://github.com/eclipse/che/issues/14248

**Comment by vparfonov** [comment] 2019-08-19 09:43
> @vparfonov could you clarify what is the difference between `7.0.0-next` & `next` ? che.openshift.io CI tests used to work just fine before the plugin version update and I do suspect this is the culprit.

`7.0.0-next ` based on 2 months old Theia,  `next` - master branch

**Comment by tsmaeder** [comment] 2019-08-19 09:44
> We can switch to the Che Theia next until not fixed [eclipse/che#14248](https://github.com/eclipse/che/issues/14248)

Are you suggesting that we switch to che-theia:next or are you saying we cannot do that because of the issue?

**Comment by ibuziuk** [comment] 2019-08-19 09:46
> 7.0.0-next based on 2 months old Theia, next - master branch

@vparfonov @tsmaeder  are we sure that `next` is working correctly against current master? if it is not the case I would propose to switch back to `7.0.0-next`

**Comment by vparfonov** [comment] 2019-08-19 10:11
i think would be better just to fix on 7.0.0, until we not found solution

**Comment by ibuziuk** [comment] 2019-08-19 12:26
Upstream issue - https://github.com/eclipse/che/issues/14283

**Comment by ibuziuk** [comment] 2019-08-21 09:08
@Katka92 I believe this one should not be reproducible anymore

**Comment by ScrewTSW** [comment] 2019-08-21 10:47
@ibuziuk the isue disappeared once the prod-preview was updated :)

**Comment by ibuziuk** [comment] 2019-08-21 10:50
Closing

**Comment by tsmaeder** [comment] 2019-08-21 11:44
@ibuziuk close the upstream issue, too?

**Comment by ScrewTSW** [comment] 2019-08-23 11:00
aaaaand the issue is back on prod-preview `starter-us-east-2a`

**Comment by Katka92** [comment] 2019-08-23 12:34
@tdancs Can you please attache the affected job?

**Comment by ScrewTSW** [comment] 2019-08-26 10:50
> @tdancs Can you please attache the affected job?

https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1253/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1251/console

**Comment by ScrewTSW** [comment] 2019-08-26 10:51
Seen today, on Saturday and Sunday:

https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1269/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1262/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1258/console

**Comment by ibuziuk** [comment] 2019-08-26 10:52
@ScrewTSW please provide investigation details. Can you reproduce the issue manually?

**Comment by ScrewTSW** [comment] 2019-08-26 10:53
> @ScrewTSW please provide investigation details. Can you reproduce the issue manually?

Haven't tried that yet. Will have a look at it.

**Comment by Katka92** [comment] 2019-08-26 10:57
For the old two jobs:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1253/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1251/console

The file was not opened correctly, so LS test failed. Please create a new issue for that and check today's failures.

**Comment by ScrewTSW** [comment] 2019-08-26 12:11
> @tdancs For the old two jobs:
> https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1253/console
> https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1251/console
> 
> The file was not opened correctly, so LS test failed. Please create a new issue for that and check today's failures.
> cc @ibuziuk

Fixed and updated in daily reports

**Comment by ibuziuk** [comment] 2019-08-27 14:48
@ScrewTSW can we close this issue ?

**Closed** 2019-08-27 20:20 UTC
Labels: kind/periodic-e2e-test, severity/blocker
