### ISSUE TITLE
PR check job fails on postgres not being able to start

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#1269] opened 2019-02-28 06:58 UTC
PR check job is failing (most of the time, not 100%) on postgresql pod not being able to start. 

Pod startup is stuck in this phase:
```
$ oc logs postgres-1-wm7vr
Initial call to run-postgresql...
=> sourcing /opt/app-root/src/postgresql-pre-start/init-debug.sh ...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/pgsql/data/userdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
```
I've tried to extend the liveness&readines probes to bigger timeouts (more than 10 minutes), but postgres never starts...

If I take a look at running processes I see this:
```
$ oc exec postgres-1-wm7vr ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1026810+   639  0.0  0.0  51736  1708 ?        Rs   06:53   0:00 ps auxf
1026810+    66  0.0  0.0  11824  1820 ?        Ss+  06:48   0:00 /bin/sh
1026810+     1  0.0  0.0  11688  1412 ?        Ss   06:47   0:00 /bin/bash /var/lib/pgsql/init-che-user-and-run.sh
1026810+    10  0.0  0.0  11820  1644 ?        S    06:47   0:00 /bin/bash /usr/bin/run-postgresql --version
1026810+    23  0.1  0.0  17556  2568 ?        S    06:47   0:00  \_ initdb
1026810+    29  0.1  0.0 241308 17788 ?        D    06:47   0:00      \_ /opt/rh/rh-postgresql96/root/usr/bin/postgres --boot -x1 -F
```

I've spent few hours yesterday trying to figure out what's happening, but with no luck.

### How to reproduce
Create some project on https://devtools-dev.ext.devshift.net:8443 cluster and switch into it.
Then do this:
```
wget https://raw.githubusercontent.com/eclipse/che/master/deploy/openshift/templates/multi/postgres-template.yaml
oc new-app -f postgres-template.yaml
```
And if you are lucky enough, postgre will not start.

**Comment by rhopp** [comment] 2019-02-28 14:24
I've created a [HK issue](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2570)

**Comment by aditya-konarde** [comment] 2019-03-01 08:41
I was able to run a Pod successfully with the template you provided, it got bound to a pv and has been running for some time now. What's the namespace you're hitting this error in? 

From my namespace: 
```
[akonarde@katana ~]$ oc get pods,pvc 
NAME                   READY     STATUS    RESTARTS   AGE
pod/postgres-1-7wdgv   1/1       Running   0          13m

NAME                                  STATUS    VOLUME                          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/postgres-data   Bound     pv-192-168-173-27-os-pv1g0095   1Gi        RWO,RWX                       13m
```

**Comment by pbergene** [comment] 2019-03-04 14:34
There is nothing indicating an infra problem here.  There are however indications of something fishy happening with the internal posgres state. Every non-working deployment has a postmaster.pid file with 26 in as opposed to pid 1 for the functional deployments.

**Comment by amisevsk** [comment] 2019-03-04 18:01
I could be entirely wrong on this, but it may be that the logs we're getting are from restarted containers -- if the first run fails and the pod is killed unceremoniously, it could potentially cause problems in recovering (which is what I've seen).

From debugging my pr-check builds, if I delete or cleanup the PVC and restart postgres it generally works. The issue is that we're not getting logs from an initial run.

**Comment by pbergene** [comment] 2019-03-05 08:09
Well, that theory got debunked quickly, now notice a few with pid68 - still consistent across pods / PVs though.

**Comment by pbergene** [comment] 2019-03-05 09:38
I've noted that the file is created and removed 3-4 times during startup. When the error occurs it is attempting to start up before this file has been cleaned up.

**Comment by ibuziuk** [comment] 2019-06-02 22:17
Haven't seen this issue for a long time. Closing as not-reproducible

**Closed by ibuziuk** 2019-06-02 22:17 UTC
Labels: kind/bug
