### ISSUE TITLE
[Infra issue] Workspace switching to offline randomly - Evicted

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1639] opened 2019-10-04 12:37 UTC
Offline state during application build caused test failure
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/d7f1d6d1-c616-4e82-a413-cde2523734fa)

Offline state during project tree expansion caused test failure
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/bb414f37-15e7-47e6-8b84-f395af6aa577)

This issue happened before once, but we thought that it was just a fringe occurence.
This time it happened twice on `1b` cluster

# EDIT:

Confirmed @amisevsk 's suspicion that this issue is connected to the Eviction errors (https://github.com/redhat-developer/rh-che/issues/1523)
When looking into the events of the workspaces that have been switched to offline mode, we can see that the eviction happens once the workspace is already started, causing the offline message:

```
{
    "kind": "Event",
    "apiVersion": "v1",
    "metadata": {
        "name": "workspacevigbckpth2bhbelq.maven-6f6f66d5d8-pj8rf.15d66587ca08e376",
        "namespace": "osiotest2-che",
        "selfLink": "/api/v1/namespaces/osiotest2-che/events/workspacevigbckpth2bhbelq.maven-6f6f66d5d8-pj8rf.15d66587ca08e376",
        "uid": "64e3ef3e-053c-11ea-95d8-02e52a0be43d",
        "resourceVersion": "1954991043",
        "creationTimestamp": "2019-11-12T11:05:53Z",
        "annotations": {
            "offending_containers": "theia-idee7w,maven,che-machine-execgwt,vscode-javazjk",
            "offending_containers_usage": "58284Ki,280Ki,252Ki,48592Ki",
            "starved_resource": "ephemeral-storage"
        }
    },
    "involvedObject": {
        "kind": "Pod",
        "namespace": "osiotest2-che",
        "name": "workspacevigbckpth2bhbelq.maven-6f6f66d5d8-pj8rf",
        "uid": "2c3a4a09-053c-11ea-a788-0233cba325d9",
        "apiVersion": "v1",
        "resourceVersion": "1954990443"
    },
    "reason": "Evicted",
    "message": "The node was low on resource: ephemeral-storage. Container theia-idee7w was using 58284Ki, which exceeds its request of 0. Container maven was using 280Ki, which exceeds its request of 0. Container che-machine-execgwt was using 252Ki, which exceeds its request of 0. Container vscode-javazjk was using 48592Ki, which exceeds its request of 0. ",
    "source": {
        "component": "kubelet",
        "host": "ip-172-31-65-163.us-east-2.compute.internal"
    },
    "firstTimestamp": "2019-11-12T11:05:53Z",
    "lastTimestamp": "2019-11-12T11:05:53Z",
    "count": 1,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
}
```

Example of an event.

**Comment by Katka92** [comment] 2019-10-07 07:33
Seen again, caused LS initialization tests failed.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1521/console

**Comment by Katka92** [comment] 2019-10-08 07:39
Workspace went off during LS initialization on cluster 2
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1526/console

**Comment by ScrewTSW** [comment] 2019-10-16 07:35
Happened today again during project tree expansion, tests couldn't open the java file on cluster `1a`
![image.png](https://images.zenhubusercontent.com/5a684d174b5806bc2bc41350/f20868c0-6755-4afd-8a5a-20178f6d7321)

**Comment by ScrewTSW** [comment] 2019-10-17 07:51
Happened twice on `1a` cluster during project tree expansion

**Comment by ScrewTSW** [comment] 2019-10-18 06:53
Seen once on `1a`

**Comment by Katka92** [comment] 2019-10-29 07:55
Seen again 1x on 2
on 1a workspace became offline during the execution of build command 2x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1443/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1444/console

**Comment by ScrewTSW** [comment] 2019-10-30 12:23
Happened yesterday twice on `2` production cluster

**Comment by ScrewTSW** [comment] 2019-11-11 12:16
Happened 6x on `1a` cluster

**Comment by ScrewTSW** [comment] 2019-11-12 08:39
happened again on `production-2` 1x
`production-1a` 2x
`production-1b` 1x

**Comment by ScrewTSW** [comment] 2019-11-13 09:10
Happened 4 times on `production-2` cluster

**Comment by ScrewTSW** [comment] 2019-11-13 10:27
Confirmed @amisevsk 's suspicion that this issue is connected to the Eviction errors (https://github.com/redhat-developer/rh-che/issues/1523)
When looking into the events of the workspaces that have been switched to offline mode, we can see that the eviction happens once the workspace is already started, causing the offline message:

```
{
    "kind": "Event",
    "apiVersion": "v1",
    "metadata": {
        "name": "workspacevigbckpth2bhbelq.maven-6f6f66d5d8-pj8rf.15d66587ca08e376",
        "namespace": "osiotest2-che",
        "selfLink": "/api/v1/namespaces/osiotest2-che/events/workspacevigbckpth2bhbelq.maven-6f6f66d5d8-pj8rf.15d66587ca08e376",
        "uid": "64e3ef3e-053c-11ea-95d8-02e52a0be43d",
        "resourceVersion": "1954991043",
        "creationTimestamp": "2019-11-12T11:05:53Z",
        "annotations": {
            "offending_containers": "theia-idee7w,maven,che-machine-execgwt,vscode-javazjk",
            "offending_containers_usage": "58284Ki,280Ki,252Ki,48592Ki",
            "starved_resource": "ephemeral-storage"
        }
    },
    "involvedObject": {
        "kind": "Pod",
        "namespace": "osiotest2-che",
        "name": "workspacevigbckpth2bhbelq.maven-6f6f66d5d8-pj8rf",
        "uid": "2c3a4a09-053c-11ea-a788-0233cba325d9",
        "apiVersion": "v1",
        "resourceVersion": "1954990443"
    },
    "reason": "Evicted",
    "message": "The node was low on resource: ephemeral-storage. Container theia-idee7w was using 58284Ki, which exceeds its request of 0. Container maven was using 280Ki, which exceeds its request of 0. Container che-machine-execgwt was using 252Ki, which exceeds its request of 0. Container vscode-javazjk was using 48592Ki, which exceeds its request of 0. ",
    "source": {
        "component": "kubelet",
        "host": "ip-172-31-65-163.us-east-2.compute.internal"
    },
    "firstTimestamp": "2019-11-12T11:05:53Z",
    "lastTimestamp": "2019-11-12T11:05:53Z",
    "count": 1,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
}
```

Example of an event.

**Comment by ScrewTSW** [comment] 2019-11-14 08:26
Happened again on `production-2` 1x
```
{
    "kind": "Event",
    "apiVersion": "v1",
    "metadata": {
        "name": "workspaceqccdnnwj7vweflkm.maven-5d7944694d-4dwk7.15ce0bfb0a8c0f48",
        "namespace": "osiotest1a-che",
        "selfLink": "/api/v1/namespaces/osiotest1a-che/events/workspaceqccdnnwj7vweflkm.maven-5d7944694d-4dwk7.15ce0bfb0a8c0f48",
        "uid": "4442531c-efdc-11e9-b0d7-121912317b4c",
        "resourceVersion": "750216911",
        "creationTimestamp": "2019-10-16T06:14:52Z",
        "annotations": {
            "offending_containers": "vscode-javalnq,maven,theia-ide3x8,che-machine-exec6kx",
            "offending_containers_usage": "680Ki,684Ki,684Ki,676Ki",
            "starved_resource": "ephemeral-storage"
        }
    },
    "involvedObject": {
        "kind": "Pod",
        "namespace": "osiotest1a-che",
        "name": "workspaceqccdnnwj7vweflkm.maven-5d7944694d-4dwk7",
        "uid": "2a1d1eab-efdc-11e9-a0c7-125c769592ce",
        "apiVersion": "v1",
        "resourceVersion": "750215929"
    },
    "reason": "Evicted",
    "message": "The node was low on resource: ephemeral-storage. Container vscode-javalnq was using 680Ki, which exceeds its request of 0. Container maven was using 684Ki, which exceeds its request of 0. Container theia-ide3x8 was using 684Ki, which exceeds its request of 0. Container che-machine-exec6kx was using 676Ki, which exceeds its request of 0. ",
    "source": {
        "component": "kubelet",
        "host": "ip-172-21-54-12.ec2.internal"
    },
    "firstTimestamp": "2019-10-16T06:14:52Z",
    "lastTimestamp": "2019-10-16T06:14:52Z",
    "count": 1,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
}
```

**Comment by skabashnyuk** [comment] 2019-11-14 08:31
@ScrewTSW do you have logs from che-master?

**Comment by amisevsk** [comment] 2019-11-14 19:31
@skabashnyuk From what I've seen, nothing special is logged on the server side when this occurs, the pod is just restarted by OpenShift.

**Comment by Katka92** [comment] 2019-11-18 08:57
This issue was seen again on 1a cluster https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1561/console and cluster 2 4x https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1770/consoleFull

**Comment by Katka92** [comment] 2019-11-19 09:03
Seen again on cluster 2 1x.

@ibuziuk According to the message [1] it seems like problems with the size of ephemeral storage. Regarding discussion with Radim, it seems to be Hosted Che related. It happens quite a lot so maybe it would be worth discussing with service delivery. They should see some peaks in disk usage [2]. In this report [3] there are twelve of `Evicted` messages, so you can read through if you would like.

[1]
`"reason": "Evicted",
 "message": "The node was low on resource: ephemeral-storage. Container vscode-javayen was using 48592Ki, which exceeds its request of 0. Container che-machine-execw1y was using 244Ki, which exceeds its request of 0. Container maven was using 248Ki, which exceeds its request of 0. Container theia-idedjt was using 58040Ki, which exceeds its request of 0. "`

[2] 
` "reason": "Evicted",
    "message": "The node was low on resource: [DiskPressure]. "`

[3] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/1781/events_report.txt

**Comment by Katka92** [comment] 2019-11-21 14:08
Seen again on cluster 2 2x and 1x on 1a. On 1a one workspace was not started because of eviction. 
![image](https://user-images.githubusercontent.com/29278800/69314810-58276c00-0c35-11ea-9733-a1c908d83da1.png)

**Comment by amisevsk** [comment] 2019-11-21 19:10
I expect it's directly related to the workspace idling issue -- it seems to come back when there are a ton of unstopped workspaces running. E.g. I could reproduce consistently before but not directly after a rollout.

**Comment by Katka92** [comment] 2019-11-22 10:24
Seen again on cluster 2 2x and on cluster 1a 3x.
I'm not sure if it is directly related to the workspace idling issue as far as it seems that workspaces were killed at ~10:10 and some failures happened at ~14:56. I would say that the idling issue made it easily reproducible but it seems there are still problems with resources on ephemeral storage.

**Comment by ScrewTSW** [comment] 2019-11-25 12:18
Seen again on production 2 x6

```
{
    "kind": "Event",
    "apiVersion": "v1",
    "metadata": {
        "name": "workspacerodpsn7u1cmy3e02.maven-c4cf469b-6x69r.15d99e49065efbf8",
        "namespace": "osiotest2-che",
        "selfLink": "/api/v1/namespaces/osiotest2-che/events/workspacerodpsn7u1cmy3e02.maven-c4cf469b-6x69r.15d99e49065efbf8",
        "uid": "c43dfe4e-0d7b-11ea-95d8-02e52a0be43d",
        "resourceVersion": "1964177575",
        "creationTimestamp": "2019-11-22T22:59:41Z",
        "annotations": {
            "offending_containers": "theia-ide5vb,vscode-javadia,che-machine-execdtp,maven",
            "offending_containers_usage": "252Ki,244Ki,244Ki,248Ki",
            "starved_resource": "ephemeral-storage"
        }
    },
    "involvedObject": {
        "kind": "Pod",
        "namespace": "osiotest2-che",
        "name": "workspacerodpsn7u1cmy3e02.maven-c4cf469b-6x69r",
        "uid": "9d285659-0d7b-11ea-a788-0233cba325d9",
        "apiVersion": "v1",
        "resourceVersion": "1964177140"
    },
    "reason": "Evicted",
    "message": "The node was low on resource: ephemeral-storage. Container theia-ide5vb was using 252Ki, which exceeds its request of 0. Container vscode-javadia was using 244Ki, which exceeds its request of 0. Container che-machine-execdtp was using 244Ki, which exceeds its request of 0. Container maven was using 248Ki, which exceeds its request of 0. ",
    "source": {
        "component": "kubelet",
        "host": "ip-172-31-65-163.us-east-2.compute.internal"
    },
    "firstTimestamp": "2019-11-22T22:59:41Z",
    "lastTimestamp": "2019-11-22T22:59:41Z",
    "count": 1,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
}
```

**Comment by ScrewTSW** [comment] 2019-11-26 12:20
Happened once on `2a produciton` cluster
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/1610/consoleFull
```
{
    "kind": "Event",
    "apiVersion": "v1",
    "metadata": {
        "name": "workspacesh5otjw0i4fivm0d.maven-574b8bbf8b-d6cv7.15da6d79c309ccb4",
        "namespace": "osiotest2aprod2-che",
        "selfLink": "/api/v1/namespaces/osiotest2aprod2-che/events/workspacesh5otjw0i4fivm0d.maven-574b8bbf8b-d6cv7.15da6d79c309ccb4",
        "uid": "2c9143fb-0f8e-11ea-8c1a-029a5a55534e",
        "resourceVersion": "1006097833",
        "creationTimestamp": "2019-11-25T14:16:29Z",
        "annotations": {
            "offending_containers": "vscode-javatct,maven,che-machine-execg94,theia-ide6ab",
            "offending_containers_usage": "692Ki,696Ki,692Ki,700Ki",
            "starved_resource": "ephemeral-storage"
        }
    },
    "involvedObject": {
        "kind": "Pod",
        "namespace": "osiotest2aprod2-che",
        "name": "workspacesh5otjw0i4fivm0d.maven-574b8bbf8b-d6cv7",
        "uid": "10f7714a-0f8e-11ea-8c1a-029a5a55534e",
        "apiVersion": "v1",
        "resourceVersion": "1006097091"
    },
    "reason": "Evicted",
    "message": "The node was low on resource: ephemeral-storage. Container vscode-javatct was using 692Ki, which exceeds its request of 0. Container maven was using 696Ki, which exceeds its request of 0. Container che-machine-execg94 was using 692Ki, which exceeds its request of 0. Container theia-ide6ab was using 700Ki, which exceeds its request of 0. ",
    "source": {
        "component": "kubelet",
        "host": "ip-172-31-68-88.us-east-2.compute.internal"
    },
    "firstTimestamp": "2019-11-25T14:16:29Z",
    "lastTimestamp": "2019-11-25T14:16:29Z",
    "count": 1,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
}
```

**Comment by ScrewTSW** [comment] 2019-11-28 12:48
Seen on `production 2` x1
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1834/consoleFull

**Comment by ScrewTSW** [comment] 2019-11-29 11:31
seen again on prod-preview `2a` x1
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/1842/consoleFull
```
{
    "kind": "Event",
    "apiVersion": "v1",
    "metadata": {
        "name": "workspace4j2yyqaafd0s8m4d.maven-5c44f87d8d-hrqqw.15db75a4a6802ad5",
        "namespace": "osio-ci-preview-testper-che",
        "selfLink": "/api/v1/namespaces/osio-ci-preview-testper-che/events/workspace4j2yyqaafd0s8m4d.maven-5c44f87d8d-hrqqw.15db75a4a6802ad5",
        "uid": "7158eb5a-1232-11ea-8c1a-029a5a55534e",
        "resourceVersion": "1007879308",
        "creationTimestamp": "2019-11-28T22:57:24Z",
        "annotations": {
            "offending_containers": "che-machine-exec8sv,vscode-javacge,theia-ideuw8,maven",
            "offending_containers_usage": "692Ki,692Ki,700Ki,696Ki",
            "starved_resource": "ephemeral-storage"
        }
    },
    "involvedObject": {
        "kind": "Pod",
        "namespace": "osio-ci-preview-testper-che",
        "name": "workspace4j2yyqaafd0s8m4d.maven-5c44f87d8d-hrqqw",
        "uid": "589c8e04-1232-11ea-8c1a-029a5a55534e",
        "apiVersion": "v1",
        "resourceVersion": "1007878207"
    },
    "reason": "Evicted",
    "message": "The node was low on resource: ephemeral-storage. Container che-machine-exec8sv was using 692Ki, which exceeds its request of 0. Container vscode-javacge was using 692Ki, which exceeds its request of 0. Container theia-ideuw8 was using 700Ki, which exceeds its request of 0. Container maven was using 696Ki, which exceeds its request of 0. ",
    "source": {
        "component": "kubelet",
        "host": "ip-172-31-69-247.us-east-2.compute.internal"
    },
    "firstTimestamp": "2019-11-28T22:57:24Z",
    "lastTimestamp": "2019-11-28T22:57:24Z",
    "count": 1,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
}
```

**Comment by Katka92** [comment] 2019-12-02 12:08
Seen again on cluster 2 2x, 1a 1x.

**Comment by Katka92** [comment] 2019-12-03 08:50
Seen again on cluster 2 2x.

**Comment by Katka92** [comment] 2019-12-04 07:19
Seen again on cluster 2 2x. Workspce not started due to Evicted state 1x on production 2a.
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1662/console

**Comment by Katka92** [comment] 2019-12-05 08:23
Seen again on cluster 2 1x

**Comment by Katka92** [comment] 2019-12-06 10:53
Seen again on cluster 2 2x
Workspace was not start due to Evicted on cluster 2 2x

**Comment by Katka92** [comment] 2019-12-11 08:55
Seen again on cluster 1a 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1702/console

**Comment by Katka92** [comment] 2019-12-13 07:36
Seen again on cluster 2 1x

**Comment by Katka92** [comment] 2019-12-16 08:27
Seen again on cluster 2 3x, 2a 1x, 1a 3x.

**Comment by Katka92** [comment] 2019-12-16 10:35
Closing this issue in favor of https://github.com/redhat-developer/rh-che/issues/1372. 
According to an agreement with @ibuziuk we will not do our standard daily comments to the PR 1372. If needed engineers will track that on Slack channel daily reports.
cc @ScrewTSW

**Comment by ScrewTSW** [comment] 2020-02-12 11:14
I'm necroing this issue :D

Seen today again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2291/console

Evicted event present in logs

**Comment by ScrewTSW** [comment] 2020-02-17 09:44
Workspace is switched to offline randomly, but there is no Evicted event present: 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2309/console

**Comment by ScrewTSW** [comment] 2020-02-21 09:34
Seen again on production cluster 2 x1:
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2344/console

Evicted present in events

**Comment by Katka92** [comment] 2020-03-12 08:15
Not observed for 20 days. Closing.

**Comment by Katka92** [comment] 2020-04-06 09:32
Seen again on cluster 2 1x - workspace didn't start
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2605/consoleFull
![image](https://user-images.githubusercontent.com/29278800/78544313-3a306180-77fa-11ea-882a-23b3ac92e249.png)

**Comment by Katka92** [comment] 2020-06-29 08:30
Workspace didn't start because of `Evicted`. 
Seen on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/3105/console

**Comment by Katka92** [comment] 2020-09-10 06:31
Workspace didn't start becuase of `Evicted`.
Seen on cluser 1a 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/3244/console

**Closed** 2020-10-02 06:16 UTC
Labels: kind/periodic-e2e-test, team/rhche-qe
