### ISSUE TITLE
Use CHE_LIMITS_USER_WORKSPACES_COUNT to avoid starting more than one workspace on OSIO via the dashboard

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/rh-che#226] opened 2017-07-26 01:20 UTC
Che server, instead of che starter should be responsible of limiting the number of running workspaces.

**Comment by amisevsk** [comment] 2017-07-26 04:36
I recall looking into this awhile ago, and the issue is that to properly implement this in che server would require changing more than just the endpoint / connector implementation, since Che does a fair bit of workspace state tracking.

The simplest solution might be to check, in e.g. `OpenShiftConnector` if a workspace is running, and if it is, first stop that workspace using the che server API, but that is a very ugly solution.

The situation may have changed in the mean time, though, so I could be wrong.

**Comment by ibuziuk** [comment] 2017-07-26 07:22
> The simplest solution might be to check, in e.g. OpenShiftConnector if a workspace is running, and if it is, first stop that workspace using the che server API, but that is a very ugly solution.
yeah, I was also thinking about this approach, but we could probably talk with Che team and figure out smth. more robust

**Comment by l0rd** [comment] 2017-07-26 07:41
That may be something to take in consideration in the SPI implementation 
cc @garagatyi @skabashnyuk @vparfonov @eivantsov

**Comment by garagatyi** [comment] 2017-07-26 08:20
Can you elaborate on what are your expectations from this feature? It is not clear whether it should stop already running WS or deny start of a second one. Also, it is not clear why you need such a feature.

**Comment by l0rd** [comment] 2017-07-26 08:51
@garagatyi currently OSIO we enforce one workspace running at a time with 1.2GB of RAM. If another workspace is already running when a user try to start a new one we stop the old one first.

**Comment by eivantsov** [comment] 2017-07-26 08:54
@l0rd are there plans to use che-starter even when a proper SPI implementation for OpenShift is in place?

**Comment by l0rd** [comment] 2017-07-26 08:58
@eivantsov che-starter should be decommissioned when we have multi tenant Che.

**Comment by garagatyi** [comment] 2017-07-26 09:04
Personally, I find auto stop experience not convenient. Why not ask the user whether he wants to stop already running WS?

**Comment by mlabuda** [comment] 2017-07-26 11:37
I was proposing this in February. There is chunk of my comment from JIRA:

> My suggestion is to slightly change behavior of the workspace master. Other words adding a functionality to let workspace master manage workspaces. There could be a property on the Che server, respectively Workspace master, which would tell how many workspaces can run at once. Few scenarios:

> Maximum number of running workspaces would be N.
a) There is M running workspaces and 0 <= M < N. User try to start an existing / new workspace. Workspace gets started.
b) There is M running workspaces and M = N. User try to start an existing / new workspace. A workspace (based on some decision, e.g. least recently used) is stopped and the desired workspace gets started.

> For use case, where N is 1 it is pretty easy with logic, because it is not necessary to implement workspace shutdown based on a decision.

**Comment by l0rd** [comment] 2017-07-26 11:58
@garagatyi I agree with you, we need to ask the user. But in OSIO the app that is responsible to interact with the user is not Che, that's the codebase UI (that's the UI that substitute the Che dashboard in OSIO). The codebase UI should ask the user if it's ok to stop the existing workspace and then will call the Che API to stop and start the new workspaces. 

But you make me think that moving the single workspace enforcement to the codebase UI may be a better solution.  Basically we need to decide if codebase UI need to do 3 calls to Che (1. get list of running workspaces 2. stop workspace 3. create workspace) or just 2 (1. get list of running workspaces 2. stop and start workspace) but I don't think we can get rid of the first call (is there any workspace running). And keeping in Codebase UI the logic to decide if we need to stop or not a workspace looks simpler. @ibuziuk @gorkem what do you think?

**Comment by ibuziuk** [comment] 2017-07-26 12:04
Moving single workspace enforcement to the codebase UI sounds relevant and user-friendly

**Comment by gorkem** [comment] 2017-07-26 13:01
Handling this on the codebases UI is not enough since you can switch between workspaces without actually going to codebases. See https://vimeo.com/226986852.

**Comment by skabashnyuk** [comment] 2017-07-26 13:35
@gorkem in codenvy we do have some logic that can block user during some operation https://github.com/codenvy/codenvy/blob/master/wsmaster/codenvy-hosted-platform-api-impl/src/main/java/com/codenvy/api/workspace/LimitsCheckingWorkspaceManager.java#L288
We check some logic during
 - workspace creation
- workspace update
- workspace start 

May be we can reuse this logic here?

**Comment by garagatyi** [comment] 2017-07-26 13:43
AFAIK it is part of permissions system. It limits wide variety of resources including amount of concurrently running workspaces

**Comment by skabashnyuk** [comment] 2017-07-26 13:45
Anyway, it will be part of multi-user Che because it limits access to the workspace to workspace owners.

**Comment by gorkem** [comment] 2017-07-27 01:37
`LimitsCheckingWorkspaceManager.java` seems to be the right place. OSIO is meant to be opinionated therefore it stops the existing workspace so `ResourceUsageManager` by itself is probably not enough.

**Comment by skabashnyuk** [comment] 2017-07-27 06:49
I'm sorry @gorkem may be I was wrong. What problem we are trying to solve?
>limiting the number of running workspaces https://github.com/redhat-developer/rh-che/issues/226#issue-245578948

**Comment by garagatyi** [comment] 2017-07-27 06:49
In my opinion, it doesn't look like a feature for Che project. Looks like it is feature and behavior of OSIO, so why to put it in Che?

**Comment by mlabuda** [comment] 2017-07-27 08:00
Well, there are more questions. Title say "Move single ws enforcement to Che server", but with upcoming changes and making Che server multitenant, operating in one cluster on OSD and managing workspaces in different cluster(s)/OpenShift instances, this feature won't be true anymore, it should be called then something like "Move single WS per user/user's project enforcement to Che server".

This feature is worth from resource point of view. We want to limit amount of workspace running per namespace (OpenShift project), because it consumes quite amount of resources and bcs of how OpenShift's resources management works. Having this feature in OSIO (e.g. in codebase) would/could not be sufficient, because users could bypass it and creates workspace against Che server manually (if no security mechanism forbidding it would not be in place).

**Comment by garagatyi** [comment] 2017-07-27 08:07
Then resources limitation should be applied in Che, so a user won't be able to start another workspace without stopping the running one. And OSIO will be able to improve this workflow by silently stopping running workspace and starting the new one.

**Comment by gorkem** [comment] 2017-07-27 13:45
Here is 2 cents
- Enforcing resource limitations should be part of upstream Che. What exists on codenvy looks perfect for this.
- We should have a plugin that will shutdown running workspaces to free resources on the OSIO assembly. This should work in conjunction with resource limitations above.

**Comment by garagatyi** [comment] 2017-07-27 13:53
I'm OK with a plugin that automatically stops WS.

**Comment by benoitf** [comment] 2017-10-10 17:13
This can be configured there: https://github.com/eclipse/che/blob/master/dockerfiles/init/manifests/che.env#L513-L566

CHE_LIMITS_USER_WORKSPACES_COUNT

**Comment by l0rd** [comment] 2017-10-11 09:24
As suggested by @benoitf it is now possible to limit the number of workspaces in upstream Che. To be able to close this issue we need to:
- set the value of `CHE_LIMITS_USER_WORKSPACES_COUNT ` to 1 using a new config map in rh-che deployment config.
- update/simplify the che launcher that used to enforce the number of running workspaces

**Comment by ibuziuk** [comment] 2017-10-11 09:38
`CHE_LIMITS_USER_WORKSPACES_COUNT` will not allow to create more than `n` workspaces, but what we have in che-starter is that when one workspace is already running and user would like to create one more, the first one would be stopped. 
@l0rd where it is planned to have the logic with stopping workspaces (should it still be in che-starter for now)?

**Comment by l0rd** [comment] 2017-10-11 09:44
@ibuziuk yes. Not sure what che API returns when you try to start a workspace and there are already `CHE_LIMITS_USER_WORKSPACES_COUNT` running but maybe now che-starter logic could be changed to always try to start a workspace without checking if there is one already running. If it fails to start the workspace che-starter will then stop the running one (hopefully the HTTP response contains the list of running workspaces). Does it makes sense?

**Comment by ibuziuk** [comment] 2017-10-11 10:02
> Not sure what che API returns when you try to start a workspace and there are already CHE_LIMITS_USER_WORKSPACES_COUNT
According to the docs error message will be returned

> maybe now che-starter logic could be changed to always try to start a workspace without checking if there is one already running. If it fails to start the workspace che-starter will then stop the running one (hopefully the HTTP response contains the list of running workspaces). Does it makes sense?

Frankly, it does not make much sense to me because  all / most of the logic  with stopping workspaces will still be in che-starter. IMO, in order to solve this issue we need to completely move the logic upstream. Maybe we could add some property like `CHE_AUTOSTOP_WORKSPACE_WHEN_LIMIT_IS_REACHED` or smth. like that

**Comment by garagatyi** [comment] 2017-10-11 12:42
@ibuziuk this behavior looks logical in OSIO, but what is the reason for this behavior in other Che installations?

**Comment by l0rd** [comment] 2017-10-11 16:10
Ok so let's set the env variable only for now.

**Comment by gorkem** [comment] 2017-10-11 19:10
@garagatyi On all openshift flavours there are quotas associated with the project. Ideally Che should be aware of those quotas on the project and stop the one running workspace to free up resources for the new request or just fail depending on the config. However today Che is not quota aware hence `CHE_LIMITS_USER_WORKSPACES_COUNT` is what can be used on it is place.

**Comment by eivantsov** [comment] 2017-10-12 05:59
yeah, it would be nice to call `/oapi/v1/namespaces/${che-workspaces-namespace}/appliedclusterresourcequotas`  (and `resourcequotas`) so that che-server can then make decisions according to results returned. For instance, our OSD has only storage quotas (100 GB for pvcs) and no resource limits.

**Comment by garagatyi** [comment] 2017-10-12 12:20
@gorkem these quotas are OpenShift specific stuff. I agree that it is a legal requirement for Che-OpenShift integration but I'm not sure how this fits our workspace API and logic.
What if the number of allowed workspaces is 3, which workspace we should stop on the start of new a workspace? BTW workspaces may have different memory consumption in case of future paid users of OpenShift. 
Don't get me wrong, I'm not against implementing features in Che useful for OpenShift, but it is not clear how it would fit Che as a standalone product.

**Comment by ibuziuk** [comment] 2018-01-02 17:12
PR is sent https://github.com/redhat-developer/rh-che/pull/496

**Comment by ibuziuk** [comment] 2018-01-09 18:48
`CHE_LIMITS_USER_WORKSPACES_RUN_COUNT` is now set on prod / prod-preview
![image](https://user-images.githubusercontent.com/1461122/34736470-54873ae2-f573-11e7-8047-63d923675e37.png)

**Closed by ibuziuk** 2018-01-09 18:48 UTC
Labels: kind/enhancement, severity/P1, sprint/current-sprint

**Comment by gorkem** [comment] 2018-01-09 22:15
Woohooo. This is from last summer.
