### ISSUE TITLE
Build Failed! / Finished: SUCCESS during PR check

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1462] opened 2019-06-19 15:30 UTC
PR check marks PR as green even if the build is failing e.g.

- https://artifacts.ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1610/console
-  https://artifacts.ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1606/console

````
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.redhat.che:fabric8-ide-parent:1.0.0-SNAPSHOT: Could not find artifact org.eclipse.che:che-parent:pom:7.0.0-RC-2.0 in codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/) and 'parent.relativePath' points at wrong local POM @ line 17, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.redhat.che:fabric8-ide-parent:1.0.0-SNAPSHOT (/root/payload/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.redhat.che:fabric8-ide-parent:1.0.0-SNAPSHOT: Could not find artifact org.eclipse.che:che-parent:pom:7.0.0-RC-2.0 in codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/) and 'parent.relativePath' points at wrong local POM @ line 17, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Error building che/rh-che with dashboard
Build Failed!
****** PR check ended at Wed Jun 19 12:14:03 BST 2019 and whole run took 218 seconds. ******
Connection to 172.19.3.89 closed.
+ rtn_code=0
+ '[' 0 -eq 0 ']'
+ cico node done 49787729
+---------+-----------+-------------+---------+------------+---------------+----------+--------+------+----------------+--------------+-----------+--------------+--------+
| host_id | hostname  | ip_address  | chassis | used_count | current_state | comment  | distro | rel  | centos_version | architecture | node_pool | console_port | flavor |
+---------+-----------+-------------+---------+------------+---------------+----------+--------+------+----------------+--------------+-----------+--------------+--------+
|      89 | n25.pufty | 172.19.3.89 | pufty   |       3635 | Deployed      | 49787729 | None   | None | 7              | x86_64       |         1 |         2240 | None   |
+---------+-----------+-------------+---------+------------+---------------+----------+--------+------+----------------+--------------+-----------+--------------+--------+
+ exit 0
Setting status of ddafa02e25c5ca67dff40708331e675aefa5cab1 to SUCCESS with url https://ci.centos.org/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/1606/ and message: 'Build finished. '
Using context: ci.centos.org PR check on dev.rdu2c.fabric8.io
### @ibuziuk The che server [build 1606] has been successfully deployed.
 http://rhche-prcheck-1445.devtools-dev.ext.devshift.net

Finished: SUCCESS
````

**Comment by ibuziuk** [comment] 2019-08-08 10:29
@Katka92 can we close this issue? I see there was a PR https://github.com/redhat-developer/rh-che/pull/1463

**Comment by Katka92** [comment] 2019-08-08 11:31
Yes, I think that after merging this PR the problem was not reproduced. Closing.

**Closed by Katka92** 2019-08-08 11:31 UTC
Labels: kind/bug
