### ISSUE TITLE
A workspace created from .NET CentOS stack fails to start

### ISSUE THREAD

**Issue by sleshchenko** [redhat-developer/rh-che#513] opened 2018-01-18 09:57 UTC
**Issue problem:** 
A workspace created from `.NET CentOS` stack fails to start.

**Red Hat Che version:** 

version: (help/about menu)
6.0.0-M5-SNAPSHOT

**Reproduction Steps:**

1. Create workspace from `.NET CentOS`.
2. Try to start it.
Expected: The workspace is started.
Actual: The workspace fails to start.

![screenshot_20180118_115441](https://user-images.githubusercontent.com/5887312/35091827-64a14326-fc46-11e7-873e-704b497370a0.png)
I've investigated this issue a bit and figured out that the issue happens because of `registry.devshift.net/che/centos_dotnet20` image and original error is:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
Warning: /home/user/che/exec-agent-linux_amd64.tar.gz: Permission denied
```

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [x] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment] 2018-01-22 13:00
Duplicate of #412 ?

**Comment by eivantsov** [comment] 2018-01-22 15:08
FYI, `eclipse/dotnet_core` works ok. I'd check permissions for user home directory in `registry.devshift.net/che/centos_dotnet20`

**Comment by l0rd** [comment] 2018-01-24 16:59
Closing because that's a duplicate

**Closed** 2018-01-24 16:58 UTC
Labels: kind/bug, sprint/next-sprint, target/multi-tenant-che6
