### ISSUE TITLE
dashboard build fail because of dist folder is not copied.

### ISSUE THREAD

**Issue by Jooho** [redhat-developer/rh-che#241] opened 2017-08-02 21:01 UTC
Hi, 

When I build redhat che using dev-scripts/build_fabric8.sh, dashboard build always fail because it 
looks for index.html to replace. However, the index.html under dist folder is not on the list to copy to ```/rh-che/target/builds/fabric8/fabric8-che/assembly/dashboard/target/patched/```

In order to fix this issue, dist folder should be added to patch list in ```/rh-che//builds/fabric8-che/assembly/dashboard/pom.xml```

```
121  <include name="e2e/**" />
122  <include name="dist/**" />    <=== ADD
```
Thanks,
Jooho Lee

**Comment by amisevsk** [comment] 2017-08-03 18:40
Hi @Jooho, I've just checked out a clean copy of rh-che and run `/rhche/dev-scripts/build_fabric8.sh`, and the build completed successfully. Could you clarify the issue you are facing?

**Comment by l0rd** [comment] 2017-08-04 15:14
Thanks @Jooho! Please provide us the steps to reproduce the issue because we have never been able to see that before.

**Comment by Jooho** [comment] 2017-08-07 15:27
Sure. 

This is full steps that I did.  I create RHEL 7U3 vm and then did following steps:

~~~
export tmp_dir=${HOME}/new/test
mkdir ${tmp_dir}
cd ${tmp_dir}

#in order to use internet from container
sysctl -w net.ipv4.ip_forward=1

# install necessary packages

yum install -y docker git wget net-tools  bridge-utils bind-utils bzip2 patch gcc bash-completion    java-1.8.0-openjdk java-1.8.0-openjdk-debug java-1.8.0-openjdk-devel java-1.8.0-openjdk-headless java-1.8.0-openjdk-headless-debug  

# oc command
yum install atomic-openshift-clients

#yum install fontconfig freetype freetype-devel fontconfig-devel libstdc++ 

# maven install 
wget http://apache.mirror.rafal.ca/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
tar xvf apache-maven-3.5.0-bin.tar.gz
mv apache-maven-3.5.0 maven


# Install nodejs(https://nodejs.org/en/download/)
wget https://nodejs.org/dist/v4.4.6/node-v4.4.6-linux-x64.tar.xz
tar xvf node-v4.4.6-linux-x64.tar.xz
mv node-v4.4.6-linux-x64 nodejs
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}


# Install golang (https://golang.org/dl)
wget https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
tar xvf go1.8.3.linux-amd64.tar.gz

# Update PATH

cat <<EOF>> ~/.bashrc
export MAVEN=\${HOME}/new/test/maven
export GOROOT=\${HOME}/new/test/go
export NODEJS=\${HOME}/new/test/nodejs
export PATH=\${MAVEN}/bin:\${GOROOT}/bin:\${NODEJS}/bin:\$PATH
EOF

source ~/.bashrc

# To avoid build error with root user
cat <<EOF> /root/.bowerrc
{
"allow_root": true,
"strict-ssl": false
 }
EOF

cat <<EOF> /root/.typingsrc
{
     "rejectUnauthorized": false,
     "registryURL": "http://api.typings.org/"
}
EOF

npm config set strict-ssl false --global
npm config set registry http://registry.npmjs.org/ --global
npm config set unsafe-perm true --global
npm install gulp bower phantomjs -g

# Download che related projects
git clone https://github.com/redhat-developer/rh-che.git

git clone https://github.com/eclipse/che-dependencies /root/new/test/che-dependencies
cd che-dependencies
git checkout openshift-connector-wip

mvn install  

cd ..
git clone https://github.com/eclipse/che
cd che
git checkout openshift-connector-wip

mvn  install  -Dfast

export UPSTREAM_CHE_PATH="${HOME}/new/test/che"
export DOCKER_HUB_NAMESPACE=docker.io/****
export DOCKER_HUB_USER=****
export DOCKER_HUB_PASSWORD=****


dev-scripts/build_fabric8.sh

~~~


This is the error messages that I encounter :
~~
INFO] [INFO] Fabric8 IDE :: Compiling WS Master WAR ............. SUCCESS [ 17.174 s]
[INFO] [INFO] Fabric8 IDE :: Che Dashboard WAR ................... FAILURE [03:40 min]
[INFO] [INFO] Fabric8 IDE :: Assemblies Tomcat ................... SKIPPED
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 13:57 min
[INFO] [INFO] Finished at: 2017-08-07T11:19:34-04:00
[INFO] [INFO] Final Memory: 118M/470M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (compile) on project fabric8-ide-che-dashboard-war: An Ant BuildException has occured: Replace: source file /root/new/test/rh-che/target/builds/fabric8/fabric8-che/assembly/dashboard/target/patched/dist/index.html doesn't exist
[INFO] [ERROR] around Ant part ...<replace file="/root/new/test/rh-che/target/builds/fabric8/fabric8-che/assembly/dashboard/target/patched/dist/index.html">... @ 7:125 in /root/new/test/rh-che/target/builds/fabric8/fabric8-che/assembly/dashboard/target/antrun/build-main.xml
[INFO] [ERROR] -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] [ERROR] 
[INFO] [ERROR] After correcting the problems, you can resume the build with the command
[INFO] [ERROR]   mvn <goals> -rf :fabric8-ide-che-dashboard-war
[INFO] ..FAILED (841.1 s)
[INFO]   The build exited with code 1. See /root/new/test/rh-che/target/builds/fabric8/fabric8-che/build.log for details.
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  fabric8-che/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:08 min
[INFO] Finished at: 2017-08-07T11:19:36-04:00
[INFO] Final Memory: 13M/164M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:2.0.0:run (RedHat assembly build) on project fabric8-ide-builder: 1 build failed. See console output above for details. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:2.0.0:run (RedHat assembly build) on project fabric8-ide-builder: 1 build failed. See console output above for details.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: 1 build failed. See console output above for details.
	at org.apache.maven.plugin.invoker.InvokerSession.handleFailures(InvokerSession.java:258)
	at org.apache.maven.plugin.invoker.InvokerMojo.processResults(InvokerMojo.java:69)
	at org.apache.maven.plugin.invoker.AbstractInvokerMojo.execute(AbstractInvokerMojo.java:741)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more

~~~

**Comment by Jooho** [comment] 2017-08-07 15:32
@amisevsk which os did you use for build? I tested 2 OS(RHEL 7.3  and Fedora 25). The thing is RHEL failed but Fedora succeed. I did same steps but the result is different..that is weird.

**Comment by benoitf** [comment] 2017-08-07 15:38
@Jooho did you build dashboard app in UPSTREAM_CHE_PATH ? ("${HOME}/new/test/che/dashboard)" before ?

**Comment by Jooho** [comment] 2017-08-07 16:21
@benoitf Yes it was built successfully

**Comment by amisevsk** [comment] 2017-08-08 17:23
@Jooho, @benoitf I've reproduced the issue now, but I'm not aware of having changed anything since last week when everything was working normally. I'm on Fedora 26 at the moment.

**Comment by l0rd** [comment] 2017-08-21 10:13
@Jooho I'm closing this issue since it should be fixed by https://github.com/redhat-developer/rh-che/pull/268. Feel free to reopen it if it's still not working for you.

**Closed by l0rd** 2017-08-21 10:13 UTC
Labels: severity/low-priority, status/info-needed
