### ISSUE TITLE
Sometimes namespace of type 'user' is missing for some users

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1043] opened 2018-11-03 19:37 UTC
**Issue problem:** 
Related `openshift.io` issue - https://github.com/openshiftio/openshift.io/issues/4564
Sometimes namespace of type 'user' is missing for some users.
Do we know why it is happening?
What should user/we do in that case?
I saw such a case with user `abazko` on prod. And resetting the tenant didn't help.

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by ibuziuk** [comment] 2018-11-04 15:58
@alexeykazakov @aslakknutsen could you please comment what is the root cause of such behavior ? We have faced this situation with absence of the user namespace quite a few times already

**Comment by alexeykazakov** [comment] 2018-11-04 16:12
@ibuziuk maybe it’s a problem with users who have similar usernames. For example:
john@gmail.com
john@redhat.com
We have a bug which prevents creating namespaces for such users.
Here a PR to fix it: https://github.com/fabric8-services/fabric8-tenant/pull/675
cc: @MatousJobanek

**Comment by ibuziuk** [comment] 2018-11-05 07:04
@alexeykazakov it is pretty unlikely that there was yet another `abazko` user registered.  Also there is  another type of issue which might be related - namespaces are created, but `/api/user/services` endpoint does not list them

**Comment by alexeykazakov** [comment] 2018-11-05 18:03
@MatousJobanek can you take a look please?

**Comment by ibuziuk** [comment] 2019-04-23 14:32
Once https://github.com/redhat-developer/rh-che/issues/1042 is resolved we would simply close this issue as won't fix (AFAIK OSIO platform team is not going to work / investigate those failures presently)

**Comment by ibuziuk** [comment] 2019-12-11 17:48
https://github.com/openshiftio/openshift.io/issues/4564 closed. Closing

**Closed by ibuziuk** 2019-12-11 17:48 UTC
Labels: kind/bug
