### ISSUE TITLE
Make the Bayesian plugin compatible with multi-tenancy token management

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#369] opened 2017-10-10 17:08 UTC
Currently, the Keycloak token injected into the Bayesian plugin is retrieved in a way that cannot work with the upstream multi-user implementation (which is becoming the basis of the `rh-che` assembly)

**Comment by l0rd** [comment] 2017-10-10 17:39
cf #248

**Comment by ibuziuk** [comment] 2017-10-31 17:25
Duplicate of https://github.com/redhat-developer/rh-che/issues/376

**Closed by ibuziuk** 2017-10-31 17:25 UTC
Labels: severity/P1, sprint/current-sprint
