### ISSUE TITLE
Che:  Auto-expand source folders instead of making the user single-click each one

### ISSUE THREAD

**Issue by RickJWagner** [redhat-developer/rh-che#99] opened 2017-06-09 14:55 UTC
When viewing a source package like 'org.jboss.demo.ejbrest.rest' the user has to select and click every.single.folder to get to the source files.

Can we change this so it acts like Eclipse, aggregating the common folders into one (or auto-opening all of them?)

Thanks for considering this issue.

**Comment by sunix** [comment] 2017-06-09 16:47
Hello, can you provide Reproduction Steps ?
Normally, java projects should have aggregating common Java packages in Che

![selection_031](https://user-images.githubusercontent.com/650571/26985531-23f3e0ec-4d44-11e7-9391-49b534a0b3d5.png)

**Comment by RickJWagner** [comment] 2017-06-09 18:01
Hello,

Thank you for the quick response.  I'll be glad to provide a reproducer.

Using a scenario similar to the Summit demo, note how the rest-microservices folder appears.  Unlike the above screenshot, there is no aggregated package under the 'Java' folder.

Screenshot below.

Thanks!




![image](https://user-images.githubusercontent.com/524520/26988059-8107b334-4d13-11e7-919c-f4c12f552b5d.png)

**Comment by amisevsk** [comment] 2017-06-09 18:10
@sunix Also in my testing: In eclipse it looks like this
![projectexplorer](https://user-images.githubusercontent.com/16168279/26988391-26c26536-4d1d-11e7-8721-1c6f05aa9ca8.png)

`/src/main/java` is squashed, and then all packages are listed at one level of depth instead of having a folder for `.org.eclipse.che.api.agent.server` with `.org.eclipse.che.api.agent.server.exception` as a subfolder.

Either way, I think this issue should be moved upstream, as it's not something we can (nor should) modify in the redhat distribution

**Comment by RickJWagner** [comment] 2017-06-09 18:32
A nice explanation passed forward via email:

The problem with the packaging is the nature of an imported project. When a project is imported into Che manually, via IDE UI, it prompts user to set a project type. If user does not set maven project type, there are no packed packages which user could unfold by a single click. Maybe more project types just than maven one behave this way and allow this functionality to work. Problem could be either when user import a project to IDE via IDE UI and dont set a maven project type right after project import. Or it could be caused by OSIO, when a user import a github project to codebase and starts a new  workspace, it imports project via API. This is done through Che starter (https://github.com/redhat-developer/che-starter/) , what is a proxy server for Che to simplify Che server calls. For now, it has dump mapping between project types and projects on github (there is a map for it and only quickstarts from OSIO are there). So in case of own code imported to a codebase and attempt to start a workspace on top of it, it created a new workspace but it did not correctly recognized project type. Workaround would be remove and import project to workspace IDE through IDE UI manually and set maven project type. Or we could enhance it in che starter - but bcs che starter is deprecated and there are other plans around whole stuff, it is hard to tell, what would be the right way.

Thanks to Marian for this.

**Comment by amisevsk** [comment] 2017-06-09 18:43
For what it's worth, regarding Marian's comment: I get the same result as @sunix's screenshot with a correctly imported project in Che, so it is being handled differently than in Eclipse.

There seem to be two issues here: 
1. Che handles displaying a java project tree differently than mainstream Eclipse
2. Regardless of 1), it would be nice if the tree in your screenshot would expand subfolders when you open the root folder. This is not Eclipse behavior but would still be a positive change IMO.

**Comment by l0rd** [comment] 2017-06-10 09:37
Since this is not a rh-che or openshift.io specific issue I will close it. 

There is a related issue upstream that has been closed too https://github.com/eclipse/che/issues/4749. @RickJWagner feel free to reopen the upstream issue if you think we still need to address something.

**Closed by l0rd** 2017-06-10 09:37 UTC
