### ISSUE TITLE
Create stacks oriented commands

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#136] opened 2017-06-27 19:01 UTC
see - https://issues.jboss.org/browse/CHE-295
@mlabuda could you please create an issue in upstream  ?

**Comment by mlabuda** [comment] 2017-06-28 07:43
Duplicate of #119

**Comment by gorkem** [comment] 2017-06-30 18:43
closing as this is a duppo

**Closed by gorkem** 2017-06-30 18:43 UTC
