### ISSUE TITLE
Impossible to import the Jenkins repository inside a Che workspace on OSIO

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#772] opened 2018-07-24 08:53 UTC
**Issue problem:** 

It is not possible to import the Jenkins repository inside a Che workspace on OSIO. A failure occurs before the end of the project import.

**Red Hat Che version:** 

Version:     1.0.0-SNAPSHOT       
Build Time:  2018-07-24 07:53:48  
Revision:    3c522aa3e596b432     
Upstream Che release: 6.8.0

 - [x] I can reproduce it on latest official image

**Reproduction Steps:**

Point your browser to the Jenkins factory available in the prod-preview OSIO instance with the following URL:
https://che.prod-preview.openshift.io/f?id=factoryqlvwzsnbpcnvwxbo

You will enter a workspace and after workspace start, after waiting for some minutes for the end of the initial project cloning, you should receive an error notification:
```
Project: jenkins Sources cannot be cloned
Internal Server Error occurred
```
and see an exception similar to this one in the `ws-machine` console output:
```
org.eclipse.jgit.api.errors.JGitInternalException: Could not delete file /projects/jenkins/core/src/main/resources/hudson/security/GlobalSecurityConfiguration/._help-disableRememberMe_bg.html7956033817958626677.tmp
```

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment] 2018-10-16 02:04
It takes more than 3 minutes to git clone jenkins github repository (it takes 15s on codenvy.io). For Kubernetes repo cloning it's 14 min vs 1 min. Timeout of a Che workspace bootstrap is 2 minutes.

To reproduce the 3 minutes git clone:

```bash
$ oc run gitclonetest --image=eclipse/che-dev:nightly -- tail -f /dev/null
eploymentconfig.apps.openshift.io "gitclonetest" deleted
$ oc volume dc/gitclonetest --add -t pvc --name=gitclonetest --claim-name=claim-che-workspace --mount-path=/workspaces
deploymentconfig "gitclonetest" updated
$ oc get po
NAME                   READY     STATUS    RESTARTS   AGE
gitclonetest-2-ghfcd   1/1       Running   0          1m
$ oc rsh gitclonetest-2-ghfcd
sh-4.2$ cd /workspaces/
sh-4.2$ time git clone https://github.com/jenkinsci/jenkins.git
Cloning into 'jenkins'...
(...)
real	3m26.303s
```

**Comment by ibuziuk** [comment] 2021-02-24 14:36
Closing as outdated. The issue is related to the gluster storage backend

**Closed by ibuziuk** 2021-02-24 14:36 UTC
Labels: codenvyio-transition, kind/bug
