### ISSUE TITLE
Bad naming of preview URL in Vert.x stack

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#92] opened 2017-06-07 04:39 UTC
_From @burrsutter on June 7, 2017 2:7_

I created a "compile vertx:run" command and it pops up a preview link of 
http://tomcat8-y5z8fqcsn2bgyg80-burrsutter-che.8a09.starter-us-east-2.openshiftapps.com//vertxbasic23/src/main/java/io/openshift/booster/HttpApplication.java
which is not valid, plus it says "tomcat" and my Vert.x app is totally not Tomcat.
https://screencast.com/t/0TcsLmpsx

_Copied from original issue: openshiftio/openshift.io#203_

**Comment by joshuawilson** [comment] 2017-06-07 04:39
@gorkem - che issue

**Comment by l0rd** [comment] 2017-06-16 17:59
Thanks @burrsutter to raise that. I've been able to reproduce it too. 

As a workaround you can modify the url:`s/http/https` and `s/tomcat8/tomcat`.

To fix that we should do a couple of things:
- https: we should use the tls redirect option for the k8s route
- fix the route (it's not tomcat8)
- change the name for the route to make it more generic (http8080 for example?)

**Comment by l0rd** [comment] 2017-07-10 14:12
tomcat8 should be fixed when this fix https://github.com/eclipse/che-dockerfiles/commit/8820f53557cabbb1c54bf6a6fb7be1b2a22789c9#diff-8cbeb0cbf990019fd81d66dfa8b46838 is ported to rhche

**Comment by davidfestal** [comment] 2017-07-18 17:15
> tomcat8 vs tomcat was fixed by @davidfestal on image eclipse/centos_jdk8 with eclipse/che-dockerfiles@8820f53#diff-8cbeb0cbf990019fd81d66dfa8b46838.

However this fix is only done in the the `eclipse/centos_jdk8` docker image. So as soon as another docker image (CentOS Vertx image for example) is used by OSIO, the fix isn't useful anymore.

But this should be finally fixed as soon as the alternate CentOS images (such as VertX) will be based on the `eclipse/centos_jdk8` image (see [this task](https://github.com/redhat-developer/rh-che/issues/147#issuecomment-316111499)).

Alternatively, we should also look into the ability to define *servers* at the Che stack level, instead of the docker image level.

**Comment by burrsutter** [comment] 2017-07-19 18:42
so, how does the end-user find the URL for his/her running app?  A Vert.x app can run inside of the Che workspace via this command
cd /projects/newspace && scl enable rh-maven33 'mvn compile vertx:run'
https://screencast.com/t/lup1mJDVLbHe

**Comment by l0rd** [comment] 2017-07-19 22:51
@ibuziuk I've noticed that when a vert.x workspace is created via osio the `attribute` field of a the stack commands is always empty:
```json
   {
      "commandLine": "scl enable rh-maven33 'mvn clean install -f ${current.project.path}'",
      "name": "build",
      "type": "mvn",
      "attributes": {}
    }
```
As a consequence, commands attributes as the preview URL are not there. Even if they are defined correctly in [stacks.json](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L2371). That behavior is not reproducible when the workspace is started from the Che dashboard.

I'm wondering if that's because we need to update the [stack model in che-starter](https://github.com/redhat-developer/che-starter/tree/master/src/main/java/io/fabric8/che/starter/model/stack).

**Comment by ibuziuk** [comment] 2017-07-20 08:29
@l0rd looks like command attributes are ignored in che-starter - https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceCommand.java#L18
I have also noticed that some stack names (wildfly-swarm / nodejs4) have been updated and not consistent with previous naming that is used in che-starter. I will provide PR

**Comment by ibuziuk** [comment] 2017-07-20 10:38
@l0rd PR is sent - https://github.com/redhat-developer/che-starter/pull/200

**Comment by l0rd** [comment] 2017-07-20 12:42
@ibuziuk great! Can you provide an update here once it is possible to test it on OSIO?

**Comment by ibuziuk** [comment] 2017-07-20 13:02
@l0rd che-starter has been updated on prod and available for testing

**Comment by l0rd** [comment] 2017-07-20 16:11
CURRENT STATUS: The preview URL is correctly shown but the hostname is the wrong one. We need to fix vertx stack Dockerfile to address that as suggested by @davidfestal [here](https://github.com/davidfestal)

**Comment by l0rd** [comment] 2017-07-21 11:15
UPDATE: After merging eclipse/che-dockerfiles#111 the preview URL is working fine now. We are not closing this issue because we still need to improve the naming of the URL (now it contains the word tomcat even if it's not served by tomcat). A good prefix for the URL would be `server8080`, `app8080`, `app-preview8080` or just `server`, `app`, `app-preview`.

**Comment by qodfathr** [comment] 2017-07-21 18:43
@l0rd, PM would like to see this labelled severity p1. Thank you.

**Comment by benoitf** [comment] 2017-08-03 11:36
I've fixed the issue.
It will take some time to be propagated as Docker images need to be build again (che + rhche images)

But now, it's possible to set per docker image any service name for a given port.

The issue was reported for Vert.x stack. Now the 8080 port will be published by a service name "vertx" so URL will have "vertx" instead of "tomcat"

**Closed** 2017-08-03 11:46 UTC
Labels: kind/bug, severity/P1, status/open-for-dev
