### ISSUE TITLE
Che: Run Command for Vertx (compile vertx:run)

### ISSUE THREAD

**Issue by joshuawilson** [redhat-developer/rh-che#95] opened 2017-06-07 04:45 UTC
_From @burrsutter on June 6, 2017 15:42_

https://screencast.com/t/3xjfAjqZJxR

Che should have an out-of-the-box run command (it has build and test-compile by default).  The run needs to be "compile vertx:run" to properly leverage the vert.x hot redeploy.   I then use Terminal to curl the endpoint
https://screencast.com/t/Ye7PLsZuwbZd

_Copied from original issue: openshiftio/openshift.io#199_

**Comment by joshuawilson** [comment] 2017-06-07 04:45
@gorkem this one is for you

**Comment by l0rd** [comment] 2017-06-16 17:46
Ok so that is really frustrating. Che vert.x stacks **has** a [run command](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L2368).

The problem is that in osio, when a user select create workspace,  [`java_centos` stack](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L1154) is always used. Even if the user has selected the vert.x base quickstart. The same applies to wildfly swarm and spring boot. Che has the stacks but these are not used in osio.

To solve that I believe we have a couple of choice:
- The quick workaround: when the user select create workspace he is prompted with five options (plain java, vertx, spring boot, wildfly swarm, node js)
- The long term solution: we inject a [chefile](https://www.eclipse.org/che/docs/chedir/chefiles/index.html) at the root of the github repository when the codebase is created. The chefiles has informations about the stack image and commands definition. 

I've opened https://github.com/fabric8io/fabric8-ui/issues/1534 for the first approach.
This ticket https://issues.jboss.org/browse/CHE-260 is about the second approach.

**Comment by ibuziuk** [comment] 2017-07-18 17:01
Related to https://github.com/redhat-developer/rh-che/issues/119
Might be already fixed - need to verify

**Comment by l0rd** [comment] 2017-07-21 09:13
This has been fixed by https://github.com/redhat-developer/rh-che/issues/216. The fix is included in Che version 1.0.234 or above.

**Closed by l0rd** 2017-07-21 09:13 UTC
Labels: kind/bug, sprint/current-sprint, status/info-needed
