### ISSUE TITLE
Ugly new user page ....

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#1876] opened 2020-04-27 15:31 UTC
When loggin the first time, che.openshift.io is showing a half broken page

![image](https://user-images.githubusercontent.com/650571/80390609-f1c20c00-88ac-11ea-8512-dc0f1836d9f9.png)

**Comment by ibuziuk** [comment] 2020-04-27 15:35
can not repro
@alexeykazakov could you please check 403 on the auth end? It looks like we have more and more issue in this field

**Comment by ibuziuk** [comment] 2020-04-27 15:44
looks like developers.redhat.com outage...

**Comment by ibuziuk** [comment] 2020-04-27 16:20
@alexeykazakov I was told that auth/resources is keycloak specific, wondering why this occasionally keep happening taking into account that auth was switched to SSO months ago

**Comment by alexeykazakov** [comment] 2020-04-27 16:42
> I was told that auth/resources is keycloak specific

Can you elaborate on that please?

**Comment by alexeykazakov** [comment] 2020-04-27 16:56
cc: @xcoulon

**Comment by ibuziuk** [comment] 2020-04-28 08:47
@alexeykazakov `/auth` used to be Keycloak maintained by the Developers program, but that was decommissioned in favour of sso.redhat.com (quote from the chat)

**Comment by alexeykazakov** [comment] 2020-04-28 09:41
Yes, we switched from RHD SSO (developers.redhat.com/auth) to sso.redhat.com a few months ago. Both are Keycloaks though.

**Comment by ibuziuk** [comment] 2020-05-07 07:18
@xcoulon @alexeykazakov is it expected a bunch of 403 / 404 errors - https://user-images.githubusercontent.com/650571/80390609-f1c20c00-88ac-11ea-8512-dc0f1836d9f9.png ?

**Comment by ibuziuk** [comment] 2020-05-12 09:47
PR sent https://github.com/redhat-developer/rh-che/pull/1889
The issue is related to the outdated links in the e2e provisioning flow after the switch to sso

**Comment by ibuziuk** [comment] 2020-05-12 14:42
The fix has been promoted to prod - https://github.com/openshiftio/saas-openshiftio/pull/1422
@Katka92 @ScrewTSW could you please verify new user registration flow?

**Comment by Katka92** [comment] 2020-05-12 15:02
I've created new user on che.openshift.io the default way and I have not seen any ugly page. :+1:

**Comment by ibuziuk** [comment] 2020-05-12 15:14
@Katka92 thanks, closing!

**Closed by ibuziuk** 2020-05-12 15:14 UTC
Labels: kind/bug, level/advanced, severity/P1, sprint/next-sprint
