### ISSUE TITLE
Build failure after rebasing `openshift-connector-wip` to the latest commit of che `5.16.0` release

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#262] opened 2017-08-10 12:14 UTC
Rebasing `openshift-connector-wip` branch to the last commit of upstream che `5.16.0` release results in build failure[1]:

> [INFO]      [exec] ├── babel-plugin-transform-es2015-parameters@6.24.1 (babel-helper-get-function-arity@6.24.1, babel-helper-call-delegate@6.24.1, babel-template@6.25.0, babel-types@6.25.0, babel-traverse@6.25.0, babel-runtime@6.25.0)
> [INFO]      [exec] └── babel-plugin-transform-regenerator@6.24.1 (regenerator-transform@0.9.11)
> [INFO]      [exec] 
> [INFO]      [exec] bower@1.8.0 node_modules/bower
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] Reactor Summary:
> [INFO] [INFO] 
> [INFO] [INFO] Fabric8 IDE (parent) ............................... SUCCESS [  3.502 s]
> [INFO] [INFO] Fabric8 IDE plugins (parent) ....................... SUCCESS [  0.059 s]
> [INFO] [INFO] Che Keycloak Shared plugin ......................... SUCCESS [ 11.775 s]
> [INFO] [INFO] Che Keycloak Token Store plugin .................... SUCCESS [  3.984 s]
> [INFO] [INFO] Che Keycloak Server plugin ......................... SUCCESS [  8.201 s]
> [INFO] [INFO] Che Keycloak IDE plugin ............................ SUCCESS [  6.202 s]
> [INFO] [INFO] Che Keycloak Token Provider plugin ................. SUCCESS [  8.670 s]
> [INFO] [INFO] Bayesian Language Server Agent ..................... SUCCESS [  4.190 s]
> [INFO] [INFO] Che :: Bayesian Language Server Integration ........ SUCCESS [  6.577 s]
> [INFO] [INFO] Fabric8 IDE assembly (parent) ...................... SUCCESS [  0.053 s]
> [INFO] [INFO] Fabric8 :: IDE :: STACKS ........................... SUCCESS [  0.114 s]
> [INFO] [INFO] Fabric8 IDE Workspace Agent War Packaging .......... SUCCESS [ 19.314 s]
> [INFO] [INFO] user-auth-valve .................................... SUCCESS [  6.302 s]
> [INFO] [INFO] Fabric8 IDE Assembly Workspace Agent Server ........ SUCCESS [  7.730 s]
> [INFO] [INFO] Fabric8 IDE :: Compiling GWT Application ........... SUCCESS [05:28 min]
> [INFO] [INFO] Fabric8 IDE :: Compiling WS Master WAR ............. SUCCESS [ 16.032 s]
> [INFO] [INFO] Fabric8 IDE :: Che Dashboard WAR ................... FAILURE [06:52 min]
> [INFO] [INFO] Fabric8 IDE :: Assemblies Tomcat ................... SKIPPED
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] BUILD FAILURE
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] Total time: 14:05 min
> [INFO] [INFO] Finished at: 2017-08-10T11:44:53+01:00
> [INFO] [INFO] Final Memory: 153M/2129M
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (compile) on project fabric8-ide-che-dashboard-war: An Ant BuildException has occured: Replace: source file /root/payload/target/builds/fabric8/fabric8-che/assembly/dashboard/target/patched/dist/index.html doesn't exist
> [INFO] [ERROR] around Ant part ...<replace file="/root/payload/target/builds/fabric8/fabric8-che/assembly/dashboard/target/patched/dist/index.html">... @ 7:117 in /root/payload/target/builds/fabric8/fabric8-che/assembly/dashboard/target/antrun/build-main.xml
> [INFO] [ERROR] -> [Help 1]
> [INFO] [ERROR] 
> [INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [INFO] [ERROR] 
> [INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [INFO] [ERROR] 
> [INFO] [ERROR] After correcting the problems, you can resume the build with the command
> [INFO] [ERROR]   mvn <goals> -rf :fabric8-ide-che-dashboard-war
> [INFO] ..FAILED (848.7 s)
> [INFO]   The build exited with code 1. See /root/payload/target/builds/fabric8/fabric8-che/build.log for details.
> [INFO] -------------------------------------------------
> [INFO] Build Summary:
> [INFO]   Passed: 1, Failed: 1, Errors: 0, Skipped: 0
> [INFO] -------------------------------------------------
> [ERROR] The following builds failed:
> [ERROR] *  fabric8-che/pom.xml
> [INFO] -------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------

This is likely to be coupled with commit[2] that allows to use docker for building dashboard. This issue is blocking us to pick up changes that are required for fixing critical  editor autosave issue [3]

[1] https://ci.centos.org/job/devtools-build-run-che-build-master/377/
[2] https://github.com/eclipse/che/commit/8fcd5dcb37adafc819379d04cdc8e31a8599215a
[3] https://github.com/openshiftio/openshift.io/issues/516

**Comment by ibuziuk** [comment] 2017-08-10 12:15
cc: @benoitf @sunix

**Comment by benoitf** [comment] 2017-08-10 12:39
there is also https://github.com/redhat-developer/rh-che/pull/242 which might be (or not) related

**Comment by amisevsk** [comment] 2017-08-10 14:13
@sunix Looks to be a duplicate of https://github.com/redhat-developer/rh-che/issues/241, there is a PR already

**Comment by benoitf** [comment] 2017-08-10 15:44
@sunix : https://github.com/redhat-developer/rh-che/commit/628235ae0b2439c408216000610ee6afeeef0dd0

**Comment by benoitf** [comment] 2017-08-10 15:45
@sunix this commit fixes the build of rh-che UD

**Comment by benoitf** [comment] 2017-08-16 09:11
fixed

**Closed by benoitf** 2017-08-16 09:11 UTC
Labels: severity/P1, sprint/current-sprint
