### ISSUE TITLE
Rolling out deployment / restarting rhche breaks workspace timeout in a bad way

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#899] opened 2018-09-20 17:50 UTC
**Issue problem:** 
When a rhche deployment is rolled out (or restarted e.g. in case of OOM -- haven't tested this exact case), the server seems to be unable to stop running workspaces due to timeout. 

Error message in logs:
```
2018-09-20 17:42:03,681[aceSharedPool-0]  [WARN ] [.Fabric8OpenShiftClientFactory 77]   - Current user ID ('0000-00-0000') is different from the user ID ('3f652e0c-1874-4de5-9c62-602634cb5cc2') that started workspace workspacem4yecw20xrdl9ls8 and subject of user that started workspace is not found in subjects cache
2018-09-20 17:42:03,703[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 485]   - Error occurs on workspace 'amisevsk-preview/wksp-dv95' with id 'workspacem4yecw20xrdl9ls8' stopped by user 'activity-checker'. Error: {}
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Error(s) occurs while cleaning up the namespace. The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:192)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:99)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:482)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:180)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:465)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Importantly: this workspace is marked `STOPPED` in che, and removed from the postgres database when this happens, but the Deployment is **not** removed. 

- If the user tries to launch the same workspace again, they will get an "Already exists error" and the workspace will be properly cleaned up
- If the user tries to launch a *different* workspace, that workspace will encounter https://github.com/eclipse/che/issues/11197.
  - If the first workspace is eventually deleted, the second workspace will start and the issue will continue
  - If the first workspace is not deleted, the second workspace will not be launchable due to already exists error, and the upstream issue will prevent cleanup. 

**Red Hat Che version:** 
 - [x] I can reproduce it on latest official image

**Reproduction Steps:**
1. Deploy Che to dev cluster.
2. (Optional) set workspace timeout lower in configmap
3. Launch a workspace
4. Once workspace is `RUNNING`, rollout a new deployment of rhche
5. Wait for workspace to timeout

Expected: Che cleans up workspace
Actual: Che thinks workspace is shut down but deployment persists.

**Comment by amisevsk** [comment] 2018-09-20 17:56
Note that this problem likely has an interplay with factories, as each load of a factory will create a new workspace. If a workspace encounters this issue, every subsequent factory load will cause another deployment to end up in the https://github.com/eclipse/che/issues/11197 state.

Also: A difference between this situation and the one described in https://github.com/eclipse/che/issues/11197 is that once quota is available, the deployment *will* start a pod. This can cause the issue to continue indefinitely (until the user manually cleans all deployments).

**Comment by amisevsk** [comment] 2018-09-20 18:10
I missed some important context in the logs:
```
2018-09-20 17:37:04,905[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 24438 ms
2018-09-20 17:42:03,525[ted-scheduler-4]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 433]   - Workspace 'amisevsk-preview/wksp-dv95' with id 'workspacem4yecw20xrdl9ls8' is being stopped by user 'activity-checker'
2018-09-20 17:42:03,678[aceSharedPool-0]  [WARN ] [.Fabric8OpenShiftClientFactory 77]   - Current user ID ('0000-00-0000') is different from the user ID ('3f652e0c-1874-4de5-9c62-602634cb5cc2') that started workspace workspacem4yecw20xrdl9ls8 and subject of user that started workspace is not found in subjects cache
2018-09-20 17:42:03,679[aceSharedPool-0]  [WARN ] [.Fabric8OpenShiftClientFactory 77]   - Current user ID ('0000-00-0000') is different from the user ID ('3f652e0c-1874-4de5-9c62-602634cb5cc2') that started workspace workspacem4yecw20xrdl9ls8 and subject of user that started workspace is not found in subjects cache
2018-09-20 17:42:03,680[aceSharedPool-0]  [WARN ] [.Fabric8OpenShiftClientFactory 77]   - Current user ID ('0000-00-0000') is different from the user ID ('3f652e0c-1874-4de5-9c62-602634cb5cc2') that started workspace workspacem4yecw20xrdl9ls8 and subject of user that started workspace is not found in subjects cache
2018-09-20 17:42:03,680[aceSharedPool-0]  [WARN ] [.Fabric8OpenShiftClientFactory 77]   - Current user ID ('0000-00-0000') is different from the user ID ('3f652e0c-1874-4de5-9c62-602634cb5cc2') that started workspace workspacem4yecw20xrdl9ls8 and subject of user that started workspace is not found in subjects cache
2018-09-20 17:42:03,681[aceSharedPool-0]  [WARN ] [.Fabric8OpenShiftClientFactory 77]   - Current user ID ('0000-00-0000') is different from the user ID ('3f652e0c-1874-4de5-9c62-602634cb5cc2') that started workspace workspacem4yecw20xrdl9ls8 and subject of user that started workspace is not found in subjects cache
2018-09-20 17:42:03,703[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 485]   - Error occurs on workspace 'amisevsk-preview/wksp-dv95' with id 'workspacem4yecw20xrdl9ls8' stopped by user 'activity-checker'. Error: {}
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Error(s) occurs while cleaning up the namespace. The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action The anonymous subject is used, and won't be able to perform this action
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesNamespace.doRemove(KubernetesNamespace.java:192)
	at org.eclipse.che.workspace.infrastructure.openshift.project.OpenShiftProject.cleanUp(OpenShiftProject.java:99)
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStop(KubernetesInternalRuntime.java:482)
	at org.eclipse.che.api.workspace.server.spi.InternalRuntime.stop(InternalRuntime.java:180)
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StopRuntimeTask.run(WorkspaceRuntimes.java:465)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by garagatyi** [comment] 2018-09-21 07:13
> and removed from the postgres database

you mean runtime info is removed from the DB, right?

We persist WS runtime in DB, but we do not persist user token corresponding to this runtime as far as I understand. When a user starts a WS his token is copied into WS start thread. But in this case, there is no user token and the error appears. 
We can:
- persist user token with the Runtime (issue may appear again if token expires which is unlikely I believe)
- use tenant lockdown. In this case, the presence of a user token in the thread context doesn't matter.

**Comment by garagatyi** [comment] 2018-09-21 07:14
Oh, and since we have a subjects cache we can also store it in the DB

**Comment by ibuziuk** [comment] 2018-09-23 17:39
I was able to reproduce the issue on the latest rh-che master, but since https://github.com/eclipse/che/issues/11197 is fixed the situation has been improved dramatically - now deployments will be always cleaned and on the second restart the workspace would be started in any case, so there will be no need to do a manual cleanup in the oso namespace. 
I would propose to promote the latest version of rh-che on prod, since pod is keep restarting on  which aggravates the issue on production - https://github.com/openshiftio/saas-openshiftio/pull/1070

**Comment by garagatyi** [comment] 2018-09-24 06:56
> I would propose to promote the latest version of rh-che on prod, since pod is keep restarting on which aggravates the issue on production

+1

BTW I think we need an issue upstream to get feedback whether this breaking state is expected or bug. @ibuziuk can you create an issue upstream?

**Comment by ibuziuk** [comment] 2018-09-24 08:16
@garagatyi @davidfestal @amisevsk oh, I thought that this problem is rh-che specific. So it is expected that workspace idling would fail the very same way in upstream after rollout ?

**Comment by davidfestal** [comment] 2018-09-24 08:42
afaik it's related to how users and OS namespaces are managed in Openshift.io.
In upstream Che, when the creating OS resources in user namespaces, the main Che SA (which is the fallback) should have the rights to modify all workspaces. So I think it should work.

But I agree with @garagatyi that it could be good to ping the upstream team about this issue, just to ensure that things are really OK there.

**Comment by garagatyi** [comment] 2018-09-24 09:11
If we talk about the inability to cleanup WS deployments then yes - it is RHChe related. But we should ensure that it is expected in upstream that WSs would fail to start in this case.

**Comment by ibuziuk** [comment] 2018-09-24 09:17
@garagatyi so, you think that if deployment exists upstream should remove it and recreate new one ? For me current upstream behaviour looks consistent but of course we could double check with upstream folks

**Comment by garagatyi** [comment] 2018-09-24 11:49
@ibuziuk I'm not talking about changing anything, just to double check that it is expected. And maybe such an issue would cause ppl to think how to improve this

**Comment by garagatyi** [comment] 2018-09-26 12:13
Discussed this with @sleshchenko and it is expected behavior for upstream Che. But we can implement a check of all WSs in the starting state on Che master start. If WS is not in an expected state we clean it up.

**Comment by garagatyi** [comment] 2018-09-26 12:16
Created upstream issue for that https://github.com/eclipse/che/issues/11364****

**Comment by ibuziuk** [comment] 2018-10-01 10:36
@davidfestal @garagatyi the fix is promoted to prod, so I believe we can close this issue

**Closed by ibuziuk** 2018-10-01 10:36 UTC
Labels: kind/bug
