### ISSUE TITLE
sso.redhat.com refused to connect on starting workspace

### ISSUE THREAD

**Issue by amisevsk** [redhat-developer/rh-che#1953] opened 2020-07-20 20:11 UTC
## Issue problem
When I start a workspace, the main Theia pane loads but shows an error page "sso.redhat.com refused to connect"

## Hosted Che version
7.15.1

## Environment
Fedora 32
Chrome Version 84.0.4147.89 (Official Build) (64-bit)

## Additional Info
![Screenshot from 2020-07-20 14-07-20](https://user-images.githubusercontent.com/16168279/87981661-da9d4f80-ca92-11ea-972c-8a7ed4ee7cfc.png)

Reproduces for me with all extensions disabled.

**Comment by ibuziuk** [comment] 2020-07-24 12:43
@amisevsk does it happen every single time for you?

**Comment by benoitf** [comment] 2020-07-24 14:26
I'm seeing that error quite often as well (timeout). Just refreshing and it's ok

**Comment by amisevsk** [comment] 2020-07-24 21:01
@ibuziuk Yeah, for all workspaces this week. The only non 200-status code request I see in my browser's dev tools is a 302 redirect.

**Comment by ibuziuk** [comment] 2020-07-27 13:57
@amisevsk @benoitf there was an sso outage. Is the issue still there?

**Comment by benoitf** [comment] 2020-07-27 14:42
I'm seeing a connection timeout/connection refused quite often when I go directly to che.openshift.io (and then being redirected to the sso login)
So in my case it was existing before and after the SSO outage. Refreshing the browser always fix the issue on my case.

**Comment by amisevsk** [comment] 2020-07-27 17:23
I'm on a different laptop today, but the issue appears to be resolved on both Chrome and Firefox. I'm :+1: to close.

**Comment by ibuziuk** [comment] 2020-08-06 13:12
sso outages happen out of the blue and are resolved in the very same manner :/
@benoitf could you please confirm that the issue is resolved before I close it?

**Comment by benoitf** [comment] 2020-08-06 13:15
let's close it I will reopen if I face again the issue

**Comment by amisevsk** [comment] 2020-08-06 17:23
I'm seeing this issue again, but only on *one* system and not another. Both are running Chrome `Version 84.0.4147.105 (Official Build) (64-bit)` :thinking: 

In my console logs on the non-working system, I see
```
Cannot load keycloak settings. This is normal for single-user mode. DOMException: Blocked a frame with origin "https://che.openshift.io" from accessing a cross-origin frame.
    at https://che.openshift.io/_app/keycloackLoader.js:21:51
    at new Promise (<anonymous>)
    at KeycloakLoader.loadKeycloakSettings (https://che.openshift.io/_app/keycloackLoader.js:19:16)
    at https://che.openshift.io/_app/loader.js:227:36
    at https://che.openshift.io/_app/loader.js:239:3
Refused to frame 'https://sso.redhat.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

**Comment by amisevsk** [comment] 2020-08-06 17:42
In incognito tabs, both systems loop on "Loading a runtime token":

![Peek 2020-08-06 13-41](https://user-images.githubusercontent.com/16168279/89564175-9cba5e00-d7ea-11ea-9fd2-450b0233f076.gif)

**Comment by sunix** [comment] 2020-08-19 10:51
We had experienced the same issue here: https://github.com/eclipse/che/issues/17472#issuecomment-676098823

**Comment by ibuziuk** [comment] 2020-08-20 13:47
Closing in favour of upstream - https://github.com/eclipse/che/issues/17472

**Closed by ibuziuk** 2020-08-20 13:47 UTC
Labels: kind/bug, severity/P1, sprint/next-sprint
