### ISSUE TITLE
[MT-che] Runtime exception when deleting workspaces (Forbidden!Configured service account doesn't have access.)

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#486] opened 2017-12-13 16:12 UTC
This is a link to openshift.io issue: https://github.com/openshiftio/openshift.io/issues/1651

**Comment by davidfestal** [comment] 2018-01-11 16:07
I couldn't reproduce this error on production: Started a workspace, then deleted it from the dashboard, and had no error:

```
{"@timestamp":"2018-01-11T15:59:15.975+00:00","@version":1,"message":"Workspace 'dfestal/wksp-ouks' with id 'workspace6a6k03bv09rc0nob' stopped by user 'dfestal'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"WorkspaceSharedPool-5","level":"INFO","level_value":20000}
{"@timestamp":"2018-01-11T15:59:16.143+00:00","@version":1,"message":"Synchronously deleting workspace workspace6a6k03bv09rc0nob on PVC claim-che-workspace","logger_name":"org.eclipse.che.plugin.openshift.client.OpenShiftConnector","thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-122","level":"INFO","level_value":20000}
{"@timestamp":"2018-01-11T15:59:16.143+00:00","@version":1,"message":"Deleting 1 workspaces on PVC claim-che-workspace","logger_name":"org.eclipse.che.plugin.openshift.client.OpenShiftConnector","thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-122","level":"INFO","level_value":20000}
{"@timestamp":"2018-01-11T15:59:16.144+00:00","@version":1,"message":"Executing command rm in PVC claim-che-workspace for 2 dirs","logger_name":"org.eclipse.che.plugin.openshift.client.OpenShiftPvcHelper","thread_name":"RemoveWorkspaceFilesAfterRemoveWorkspaceEventSubscriber-122","level":"INFO","level_value":20000}
{"@timestamp":"2018-01-11T15:59:16.159+00:00","@version":1,"message":"Workspace 'workspace6a6k03bv09rc0nob' removed by user 'dfestal'","logger_name":"org.eclipse.che.api.workspace.server.WorkspaceManager","thread_name":"http-nio-8080-exec-7","level":"INFO","level_value":20000,"req_id":"97a437cb-f83e-4b1c-bb67-2ec57491d7d4","identity_id":"469d0b51-8fb7-4f6b-82a3-bca0f9f7d876"}
```

It might be that the root cause of the initial error would have been fixed by some other fix.

Maybe @rhopp could test again to confirm

**Comment by rhopp** [comment] 2018-01-12 08:37
@davidfestal I managed to get some errors [1] doing this:
1) have multiple workspaces.
2) Delete them all in dashboard.
3) Immediately reset env in openshift.io
4) Profit! (errors appears in log)

That's probably because deleting multiple workspaces spawns multiple "delete pods" on OSO and when I push reset account, some of those pods gets killed, but che don't know that and tries to communicate with them, which results in errors.

But I do get this is pretty corner case.. Errors in log are OK in this case I guess... And on top of that - user does not notice any difference (everything works, workspaces are deleted as expected).

[1] - https://pastebin.com/sVY4qewk

**Comment by rhopp** [comment] 2018-08-31 12:06
I wasn't able to reproduce this issue on latest che on prod. Closing.

**Closed by rhopp** 2018-08-31 12:06 UTC
Labels: kind/bug, severity/low-priority
