### ISSUE TITLE
[Che Issue] Maven terminal reset during build

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#1633] opened 2019-09-30 13:46 UTC
For some strange reason the terminal output got reset during application build.

![image](https://user-images.githubusercontent.com/16451875/65884611-72616e00-e399-11e9-8c90-be7fc944e43f.png)

![image](https://user-images.githubusercontent.com/16451875/65884624-79887c00-e399-11e9-82b1-f62bb3d55ef8.png)

This issue appeared three times during the weekend on production `1b` cluster.

**Comment by Katka92** [comment] 2019-10-08 07:39
Seen again on 2a https://ci.centos.org/job/devtools-rh-che-periodic-prod-2aProd/1320/console

**Comment by Katka92** [comment] 2019-10-10 06:41
Seen again on 1a https://ci.centos.org/job/devtools-rh-che-periodic-prod-1a/1329/console

**Comment by ScrewTSW** [comment] 2019-10-15 11:08
happened again in the `Vert.x` stack test today on `1a`

**Comment by ibuziuk** [comment] 2019-10-15 11:11
@ScrewTSW @Katka92 do we have an issue for upsrtream (this does not look Hosted Che specific)?

**Comment by Katka92** [comment] 2019-10-29 07:53
Seen again on 1b https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/1421/console

**Comment by Katka92** [comment] 2019-11-19 09:03
Seen again on 1b.

**Comment by Katka92** [comment] 2019-12-11 08:39
Not reproduced for 22 days. Closing.

**Comment by Katka92** [comment] 2020-02-07 08:32
Seen again on production cluster 2a.

**Comment by Katka92** [comment] 2020-02-28 07:31
Seen on production 1b cluster 1x https://ci.centos.org/job/devtools-rh-che-periodic-prod-1b/2173/console

**Comment by ScrewTSW** [comment] 2020-03-02 13:35
seen again on production cluster 2a x2:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2179/console
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2183/console
on production cluster 1b x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/2194/console

**Comment by ScrewTSW** [comment] 2020-03-04 08:32
Seen again on production cluster 2a x1:
https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/2204/console

**Comment by Katka92** [comment] 2020-04-06 09:29
Seen again on cluster 2 1x
https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/2600/console

**Comment by Katka92** [comment] 2020-05-04 09:45
Now we have a video and the reason for that failure seems to be clear. The workspace switches to offline and then the terminal output is removed and the command is kind of stopped.
See the video [1] from 1:12.
It's not clear to me why the workspace turned to offline. There are some 403 in browser logs [2] but I'm not sure if those are related to the problem. There is no `evicted` event in events log [3].

[1] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/2774/e2e_report/report/ffmpeg_report/output.mp4
[2] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/2774/e2e_report/report/Java_Maven_test_Validation_of_workspace_build_and_run_Run_command_'maven_build'/browserlogs-Run_command_'maven_build'.txt
[3] http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/2774/events_report.txt

Seen again on cluster 2 1x
Seen on prod-preview cluster 2a 2x 
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2778/console
https://ci.centos.org/job/devtools-rh-che-periodic-prod-preview-2a/2779/console

**Comment by Katka92** [comment] 2020-05-18 06:44
Closing in favour of https://github.com/redhat-developer/rh-che/issues/1848 as this issue describes the root cause.

**Closed by Katka92** 2020-05-18 06:44 UTC
Labels: kind/periodic-e2e-test, team/rhche-qe
