### ISSUE TITLE
Unable to run workspace on prod-preview (multitenant)

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/rh-che#468] opened 2017-12-05 15:15 UTC
**Issue problem:** 
I'm unable to run workspace on prod-preview using multitenant account:
Che log:
```
2017-12-05 15:13:14,540[aceSharedPool-7]  [WARN ] [.e.c.p.d.m.MachineProviderImpl 569]  - Failed to check image che/vertx availability. Cause: Unable connect to unix socket: '/var/run/docker.sock'
2017-12-05 15:13:14,676[aceSharedPool-7]  [INFO ] [c8WorkspaceEnvironmentProvider 197]  - Retrieving user Che tenant data
2017-12-05 15:13:14,796[aceSharedPool-7]  [INFO ] [c8WorkspaceEnvironmentProvider 230]  - cheTenantData = {kkanova-osiotest1-che,https://api.free-int.openshift.com,null}
2017-12-05 15:13:16,978[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1050] - Created ImageStream registry.devshift.net_che_vertx.
2017-12-05 15:13:19,138[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1825] - Created ImageStreamTag registry.devshift.net_che_vertx:1qahif3zrrp4zhbkiyhmso5nmbexal in namespace kkanova-osiotest1-che
2017-12-05 15:13:19,139[aceSharedPool-7]  [WARN ] [o.e.c.p.o.c.OpenShiftConnector 569]  - Didn't find image 'eclipse-che/workspace1qahif3zrrp4zhbk_machineiyhmso5nmbexal1m_kkanova-osiotest1_dev-machine' in the map of created images
2017-12-05 15:13:19,275[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1616] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
2017-12-05 15:13:19,612[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1616] - imageStreamTag dockerImageConfig empty. Using dockerImageMetadata to get image info
2017-12-05 15:13:19,614[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 655]  - Che property 'che.openshift.workspace.memory.override' used to override workspace memory limit to 2.4Gi.
2017-12-05 15:13:19,697[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1679] - OpenShift service che-ws-1qahif3zrrp4zhbk created
2017-12-05 15:13:19,772[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route wsagent-1qahif3zrrp4zhbk created
2017-12-05 15:13:19,844[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route exec-agent-1qahif3zrrp4zhbk created
2017-12-05 15:13:19,911[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route server-4403-tcp-1qahif3zrrp4zhbk created
2017-12-05 15:13:19,978[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route terminal-1qahif3zrrp4zhbk created
2017-12-05 15:13:20,043[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route server-22-tcp-1qahif3zrrp4zhbk created
2017-12-05 15:13:20,112[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route vertx-debug-1qahif3zrrp4zhbk created
2017-12-05 15:13:20,177[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route tomcat8-debug-1qahif3zrrp4zhbk created
2017-12-05 15:13:20,247[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route vertx-1qahif3zrrp4zhbk created
2017-12-05 15:13:20,314[aceSharedPool-7]  [INFO ] [.c.p.o.c.OpenShiftRouteCreator 82]   - OpenShift route codeserver-1qahif3zrrp4zhbk created
2017-12-05 15:13:20,315[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1713] - Creating OpenShift deployment che-ws-1qahif3zrrp4zhbk
2017-12-05 15:13:20,315[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 1718] - Adding container 1qahif3zrrp4zhbk-machineiyhmso5nmbexal1m-kkanova-osiotest1-dev to OpenShift deployment che-ws-1qahif3zrrp4zhbk
2017-12-05 15:13:20,315[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 35]   - Container environment variables:
2017-12-05 15:13:20,315[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - EXEC_AGENT_LOGS_DIR_SETTER=export EXEC_AGENT_LOGS_DIR="/workspace-logs/${CHE_MACHINE_NAME}-exec-agent"
2017-12-05 15:13:20,316[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - MAVEN_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m
2017-12-05 15:13:20,316[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_LOCAL_CONF_DIR=/mnt/che/conf
2017-12-05 15:13:20,316[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_LOGS_DIR_SETTER=export CHE_LOGS_DIR="/workspace-logs/${CHE_MACHINE_NAME}-ws-agent"
2017-12-05 15:13:20,316[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - USER_TOKEN=machines59ljmgpvhpq1hhgtp8c7luxa6u6hvmht7kz8xtahgowqy5i35rph3m2m8xyayyl4niqkid173dqae82sd2f2rzjfthhlzbii1d05e224yy9ljr8wocgug7szhfstmex
2017-12-05 15:13:20,316[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_MACHINE_NAME=dev-machine
2017-12-05 15:13:20,316[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m
2017-12-05 15:13:20,317[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_WORKSPACE_ID=workspace1qahif3zrrp4zhbk
2017-12-05 15:13:20,317[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_PROJECTS_ROOT=/projects
2017-12-05 15:13:20,317[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_IS_DEV_MACHINE=true
2017-12-05 15:13:20,317[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.k.KubernetesEnvVar 43]   - - CHE_API=https://che.prod-preview.openshift.io/wsmaster/api
2017-12-05 15:13:20,392[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 722]  - Error while creating Pod, removing deployment
2017-12-05 15:13:20,392[aceSharedPool-7]  [INFO ] [o.e.c.p.o.c.OpenShiftConnector 723]  - Failure executing: POST at: https://api.free-int.openshift.com/api/v1/namespaces/kkanova-osiotest1-che/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
2017-12-05 15:13:20,455[aceSharedPool-7]  [WARN ] [p.o.c.k.KubernetesResourceUtil 43]   - No Deployment with name che-ws-1qahif3zrrp4zhbk could be found
2017-12-05 15:13:20,656[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route codeserver-1qahif3zrrp4zhbk
2017-12-05 15:13:20,726[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route exec-agent-1qahif3zrrp4zhbk
2017-12-05 15:13:20,737[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route server-22-tcp-1qahif3zrrp4zhbk
2017-12-05 15:13:20,751[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route server-4403-tcp-1qahif3zrrp4zhbk
2017-12-05 15:13:20,761[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route terminal-1qahif3zrrp4zhbk
2017-12-05 15:13:20,772[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route tomcat8-debug-1qahif3zrrp4zhbk
2017-12-05 15:13:20,786[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route vertx-1qahif3zrrp4zhbk
2017-12-05 15:13:20,799[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route vertx-debug-1qahif3zrrp4zhbk
2017-12-05 15:13:20,809[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 93]   - Removing OpenShift Route wsagent-1qahif3zrrp4zhbk
2017-12-05 15:13:20,819[aceSharedPool-7]  [INFO ] [o.c.OpenShiftDeploymentCleaner 99]   - Removing OpenShift Service che-ws-1qahif3zrrp4zhbk
2017-12-05 15:13:20,997[aceSharedPool-7]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 683]    - Failure executing: POST at: https://api.free-int.openshift.com/api/v1/namespaces/kkanova-osiotest1-che/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
org.eclipse.che.api.core.ServerException: Failure executing: POST at: https://api.free-int.openshift.com/api/v1/namespaces/kkanova-osiotest1-che/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1005)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:797)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:263)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:694)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:103)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:986)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:948)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:31)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.che.api.core.ServerException: Failure executing: POST at: https://api.free-int.openshift.com/api/v1/namespaces/kkanova-osiotest1-che/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:401)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:768)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:942)
        ... 11 common frames omitted
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.free-int.openshift.com/api/v1/namespaces/kkanova-osiotest1-che/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:320)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:239)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:210)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:699)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:324)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.getClaimCheWorkspace(OpenShiftConnector.java:2084)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.getVolumeMountsFrom(OpenShiftConnector.java:1999)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createOpenShiftDeployment(OpenShiftConnector.java:1736)
        at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createContainer(OpenShiftConnector.java:701)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:648)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:357)
        ... 13 common frames omitted
```

**Red Hat Che version:** 

version: 5.21.0

**Reproduction Steps:**

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment] 2017-12-11 13:26
Looks like related to PROD PREVIEW since not reproducible in PROD. So setting as Low Priority

**Comment by ScrewTSW** [comment] 2018-04-04 11:57
@l0rd maybe can be closed? outdated issue?

**Comment by l0rd** [comment] 2018-04-05 22:09
@ScrewTSW yes closing

**Closed by l0rd** 2018-04-05 22:09 UTC
Labels: kind/bug, severity/low-priority
