### ISSUE TITLE
Che projects do not have maven nature in OSIO (spring-boot / vertx stacks) 

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#228] opened 2017-07-26 10:38 UTC
When a new workspace is created in OSIO from the codebase UI it doesn't appear as a maven project. I've been able to reproduce it both spring-boot and vertx quickstarts.

As a result jUnit support doesn't work. The workaround is to set the maven nature manually via `Project -> Update Project configuration`.

![image](https://user-images.githubusercontent.com/606959/28617078-3ed8352c-71ff-11e7-93e2-048f3ccd717c.png)

**Comment by ibuziuk** [comment] 2017-07-26 10:54
might be related to - https://github.com/redhat-developer/che-starter/issues/113
in che-starter we are setting both `type` and `projectType` but it still fails for some reason :/

cc: @mlabuda

**Comment by mlabuda** [comment] 2017-07-26 12:47
Hmm, it could be related to this https://github.com/redhat-developer/che-starter/commit/fc95e06c97d7949a94b23c2236cbc63f3c728934 or to the StackProjectMapping class. We have static mapping and now we have changed some IDs but it required to have also updated Che server which reflects the same IDs.

**Comment by ibuziuk** [comment] 2017-07-26 13:02
@mlabuda but `spring-boot` stack should not be affected by redhat-developer/che-starter@fc95e06

**Comment by ibuziuk** [comment] 2017-07-26 13:07
Correct project type is set correctly for `java-centos` stack:

![image](https://user-images.githubusercontent.com/1461122/28622207-ffa9d062-7213-11e7-9992-6d82e3fb0915.png)

**Comment by ibuziuk** [comment] 2017-07-26 14:21
@l0rd just tested against spring-boot "quick-start" and project-type "maven" was set correctly:


> {"time":"2017-07-26T14:16:39.429+00:00","msg":"Creating project against workspace agent URL: https://wsagent-fx3lzzoqp8xwf5tp-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com/api/project/batch","logger":"io.fabric8.che.starter.client.ProjectClient","thread":"SimpleAsyncTaskExecutor-21","level":"INFO","HOSTNAME":"che-starter-22-okvi5"}
> --
>   | 2017-07-26 14:16:39.431  INFO 1 --- [TaskExecutor-21] i.f.che.starter.client.ProjectClient     : Project type: maven
>   | {"time":"2017-07-26T14:16:39.431+00:00","msg":"Project type: maven","logger":"io.fabric8.che.starter.client.ProjectClient","thread":"SimpleAsyncTaskExecutor-21","level":"INFO","HOSTNAME":"che-starter-22-okvi5"}

**Comment by ibuziuk** [comment] 2017-07-26 14:28
the same is for vertx: 

```
{"time":"2017-07-26T14:27:25.024+00:00","msg":"Creating project against workspace agent URL: https://wsagent-6st720v1d6isfrgu-ibuziuk-che.8a09.starter-us-east-2.openshiftapps.com/api/project/batch","logger":"io.fabric8.che.starter.client.ProjectClient","thread":"SimpleAsyncTaskExecutor-22","level":"INFO","HOSTNAME":"che-starter-22-okvi5"}
--
  | 2017-07-26 14:27:25.024  INFO 1 --- [TaskExecutor-22] i.f.che.starter.client.ProjectClient     : Project type: maven

```

**Comment by l0rd** [comment] 2017-07-27 08:00
Thanks @ibuziuk for investigating. I will test again from a clean environment (removing old stacks.json) and will provide an update here.

**Comment by bmicklea** [comment] 2017-08-02 13:59
FYI - prioritized as P2 in the IO Workshop kill list.

**Comment by ibuziuk** [comment] 2017-08-02 14:00
@l0rd are you able to reproduce ?

**Comment by bmicklea** [comment] 2017-08-02 14:34
FWIW, it's intermittent for me.

**Comment by ibuziuk** [comment] 2017-08-02 15:00
@bmicklea does refresh help? just speculation but the root of the problem might be the same as for Git menu items - https://github.com/redhat-developer/rh-che/issues/230#issuecomment-319696982

**Comment by bmicklea** [comment] 2017-08-02 15:03
Tried that but it didn't help. I had to go into the project config and change from "blank" to "maven" manually.

**Comment by ibuziuk** [comment] 2017-08-02 15:09
@bmicklea ok, thanks for clarifications - than it is smth. else

**Comment by ibuziuk** [comment] 2017-08-02 15:17
@bmicklea you was able to reproduce against vert.x quickstart, right ?

**Comment by bmicklea** [comment] 2017-08-02 15:19
Yes correct

**Comment by eivantsov** [comment] 2017-08-03 07:22
@ibuziuk are you absolutely confident that when ` Project type: maven` is in che-starter logs, response from ws-agent is the same? I mean, the project is created as mvn?

**Comment by ibuziuk** [comment] 2017-08-03 07:26
@eivantsov since I'm not able to reproduce so far - yes. But I need to play with it more since this one is intermittent according to Brad

**Comment by eivantsov** [comment] 2017-08-03 07:37
@ibuziuk as with the misconfigured project issue, I do think that the problem is somewhere in che-starter-ws-master or che-starter-ws-agent (as in this case) chain... since if you directly create a workspace by interacting with master (User Dashbard or any REST client tool) ad import a project in the same way, the problem cannot be reproduced.

I'd probably debug ws-agent when the project is imported by che-starter. I tried to connect using the route that OS has created, but failed.

**Comment by ibuziuk** [comment] 2017-08-03 12:14
@eivantsov @l0rd @bmicklea @burrsutter I still can not reproduce the issue (neither on osio, nor locally), please ping me in MM when you have some time and we will investigate it together since I need input from someone who can repro this error. 

Some updates:

We talked with Eugene today and he told  that the issue is **not** reproducible when che-starter was running locally, and is **always** reproducible on osio. We figure out that che-starter that was running locally was not up-to-date and after pulling the latest version Eugene start  **always** getting this issue locally. So, this is supposed to be che-starter issue, but I can not spot so far what is causing it. The version that was working locally was cloned on **Jul 21** and there are only a few commits that might cause this project type issue -  https://github.com/redhat-developer/che-starter/commits/master
The most suspicious is this one[1], but I do not understand so far how this might be related to the import issue. So, please ping me when you have some time and I believe we would be able to tackle it together.


[1] https://github.com/redhat-developer/che-starter/commit/d8751aa963f768aec671f8c218d7dc96110f8baa

**Comment by ibuziuk** [comment] 2017-08-04 14:02
@bmicklea @slemeur @eivantsov Basically, we had a problem [1] some time ago with red cross on imported project and it was fixed by changing **"type"** to **"projectType"** property. However, when we set only **"projectType"** the project nature was always blank [2] (Comment from the issue - https://github.com/redhat-developer/che-starter/issues/113#issuecomment-292430405). So, it was decided to set both **"type" / "projectType"** during project creation. Could this potentially cause this problem ?

[1] https://issues.jboss.org/browse/CHE-133
[2] https://github.com/redhat-developer/che-starter/issues/113

**Comment by ibuziuk** [comment] 2017-08-04 14:12
In project templates "projectType" is used [1], but using `api/workspace` endpoint I can see only "type" property for newly created projects on osio:

```
"projects": [
  {
"problems": [],
"links": [],
"mixins": [],
"description": "Created via che-starter API",
"source": {
"location": "https://github.com/l0rd/testmavennature.git",
"type": "git",
"parameters": {
"branch": "master",
"keepVcs": "true"
}
},
"name": "testmavennature",
"type": "maven",
"path": "/testmavennature",
"attributes": {
"contribute_to_branch": [
  "master"
],
}
}
]
```
So, what properties supposed to be set during project creation via `project/batch` endpoint ? In che-starter this is done the following way [2]
[1] https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json#L7
[2] https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/client/ProjectClient.java#L154

**Comment by eivantsov** [comment] 2017-08-04 14:18
@ibiziuk it should be `type`. samples.json is used by User Dashboard and we filter stacks and corresponding samples there. Not sure though why a different name is used there.. Anyway, you may want to try to change it to `type` and test with a local che-starter.

**Comment by ibuziuk** [comment] 2017-08-04 14:44
@eivantsov yeah, I tested it and I can not repro red cross issue[1] anymore. So, I will set only "type" property during creation. 

[1] https://issues.jboss.org/browse/CHE-133

**Comment by ibuziuk** [comment] 2017-08-04 16:48
PR[1] for removing 'projectType' and already available on prod. Please, let me know if you still can reproduce the issue.
[1] https://github.com/redhat-developer/che-starter/pull/210

**Comment by bmicklea** [comment] 2017-08-04 18:04
@ibuziuk I'm using IO with Che 1.0.265.  I am still seeing an odd behavior. I can reproduce this every time with these steps:
1. Create a workspace from IO
1. From the Codebase tab create a Che workspace

Expected result:
Che opens, project has the correct type, all language services work.

Actual result:
When Che opens, the imported project shows up first with a red "x" on it. However, if I open the project I can use Java intellisense and other maven project type features. If I go into the project configuration it shows it configured to "Blank".  If I then refresh the browser the project shows the correct icon and project configuration shows Maven correctly.

You can see a video of the behavior here: https://vimeo.com/228405926

**Comment by ibuziuk** [comment] 2017-08-06 06:55
FYI, I have created a separate issue for "Test" menu items which are disabled sometimes even with "maven" Project type - https://github.com/redhat-developer/rh-che/issues/252

**Comment by ibuziuk** [comment] 2017-08-06 07:03
@bmicklea thanks for the demo:

> You can see a video of the behavior here: https://vimeo.com/228405926

@eivantsov could this happen for the same reason as "Git" menu items problem? refresh seem to tackle both issues?

**Comment by ibuziuk** [comment] 2017-08-18 12:47
@ldimaggi @rhopp @Katka92  could you please verify this issue on prod ?
@bmicklea @burrsutter  the project import logic has been **significantly** changed, so please let me know if all works for you

**Comment by ibuziuk** [comment] 2017-08-23 18:16
Verified against che 1.0.294
Closing

**Closed by ibuziuk** 2017-08-23 18:16 UTC
Labels: kind/bug, severity/P1, sprint/current-sprint
