### ISSUE TITLE
Simplify deployment of che-server on osio/minishift

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/rh-che#572] opened 2018-03-06 15:19 UTC
**Issue problem:** 
We need a way to make deployment of che-server easier on the user, simplifying/automating the steps.

**Red Hat Che version:** 

version: 5.22.x & 6.1.x

**Runtime:**

runtime used:
   - [X] minishift (include output of `minishift version`)
   - [X] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by l0rd** [comment] 2018-03-26 11:53
@ScrewTSW  closing because it looks like a duplicate of #489 #540. Feel free to re-open

**Closed by l0rd** 2018-03-26 11:53 UTC
Labels: kind/enhancement
