### ISSUE TITLE
PR CI ignores unresolved conflicts on rebasing PR branch against master branch

### ISSUE THREAD

**Issue by garagatyi** [redhat-developer/rh-che#1168] opened 2019-01-03 12:24 UTC
**Issue problem:** 
CI rebases PR branch against master branch:
```shell
Installed:
  rsync.x86_64 0:3.1.2-4.el7                                                    

Complete!
+ '[' -n master ']'
+ git rebase --preserve-merges origin/master
```
But when a conflict that cannot be automatically resolved occurs CI ignores that and files are kept broken (with merge resolution lines):
```shell
Complete!
+ '[' -n master ']'
+ git rebase --preserve-merges origin/master
Rebasing (1/2)
Auto-merging openshift/rh-che.app.yaml
CONFLICT (content): Merge conflict in openshift/rh-che.app.yaml
Auto-merging openshift/minishift-addons/rhche/templates/rh-che.app.yaml
CONFLICT (content): Merge conflict in openshift/minishift-addons/rhche/templates/rh-che.app.yaml
Automatic merge failed; fix conflicts and then commit the result.
Error redoing merge 3703360e415e1a68600a8a72c2103248d0477001
++ pwd
+ rsync -e 'ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root' -Ha /home/devtools/workspace/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/ 172.19.2.174:payload
```

Instead of that CI should stop the build immediately in this situation. Because when we is keeping the build process running errors that appear later way less clear and make us spend more time investigating. 

**Red Hat Che version:** 

version: (help/about menu)

 - [ ] I can reproduce it on latest official image

**Reproduction Steps:**

Describe how to reproduce the problem

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [ ] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)
   - [ ] k8s (include output of `kubectl version`)

**Comment by Katka92** [comment] 2019-03-27 09:11
@garagatyi The rebase is executed by script hardcoded in devtools-ci-index.yaml [1]. And the root cause why it is not failing is this [2]. As far as this script is used by many teams, I don't want to do changes here. I've asked service delivery, if that behaviour is intended but I'm afraid they won't be able to answer the question. So we should probably do some check on our side. One of things that come on my mind is to do rebase again in our scripts so we can handle that the way we want. If you have any other ideas or suggestions, please let me know.

[1] https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L514
[2] https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L479

**Comment by garagatyi** [comment] 2019-03-27 10:01
I believe it is a bug in the script. They disable exit on error and use explicit return code checking (e.g. https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml#L488) and they do not do this check for the rebase command. We just need to add this check to that script. I mean upstream.
Can you handle that or you would rather leave it to me?

**Comment by Katka92** [comment] 2019-03-27 10:59
I can handle that. Thank you for your opinion. :+1:

**Comment by Katka92** [comment] 2019-03-27 11:20
PR was created: https://github.com/openshiftio/openshiftio-cico-jobs/pull/993

**Comment by ibuziuk** [comment] 2020-05-11 10:55
@Katka92 PR is merged. Can we close the issue?

**Closed** 2020-05-11 12:23 UTC
Labels: kind/bug
