### ISSUE TITLE
OpenShift branch Docker strategies to update before going to master branch

### ISSUE THREAD

**Issue by benoitf** [redhat-developer/rh-che#113] opened 2017-06-16 19:25 UTC
Currently, the openshift branch contains local-docker and single-port strategies.

The single-port strategy is in conflict with the custom strategy in master.
This custom strategy allows to customize the URLs returned to clients by using a template.

The single port strategy is having a "hard-coded" value of this URL format and it may work only for OpenShift.io usecase so it can't be merged to "Che" like this.

So, before the merge to master, the single-port strategy needs to be removed and the custom strategy needs to be used

- Custom strategy needs to be enhanced with a property allowing to customize the internal address (gateway address usage) 

- https://github.com/fabric8io/fabric8-online/blob/master/apps/che/src/main/fabric8/deployment.yml will have to contain the OpenShift.io template, and the property allowing to use gateway internal IP

- these properties will also need to be updated : https://github.com/redhat-developer/rh-che/blob/148fc268b6a7b26574220ad1de715ff6140fb5ce/dev-scripts/create-all.sh#L46

**Comment by davidfestal** [comment] 2017-06-16 19:39
The strategy classes have already been refactored to allow this. So this will be mainly changing properties, and configuration.

**Comment by l0rd** [comment] 2017-06-19 00:06
This issue may be a duplicate of https://issues.jboss.org/browse/CHE-277. If that's the case @benoitf we should probably close one of the two issues.

**Comment by benoitf** [comment] 2017-06-19 05:40
I will let @davidfestal decide as he asked to me create this issue.

**Comment by davidfestal** [comment] 2017-06-19 08:39
@l0rd This issue is the result of a discussion I had with @benoitf about the work done in CHE-277, and changes he thought would still be necessary in this area before merging to master. Since CHE-277 was already fixed and merged to the `openshift-connector-branch`, I though we should track this in a new issue. I'll work on it at the beginning of the week. It's not much work: mainly configuration changes.

**Comment by l0rd** [comment] 2017-06-19 23:09
@davidfestal ok so I think it makes sense to close CHE-277 no?

**Comment by davidfestal** [comment] 2017-06-20 08:02
@mario  yes, you're right. done.

**Closed** 2017-07-04 16:11 UTC
Labels: kind/task, sprint/current-sprint
