### ISSUE TITLE
Need to verify that ssh plugin works correctly in Hosted Che

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#1524] opened 2019-07-30 11:59 UTC
Need to verify that ssh plugin works correctly in Hosted Che and once configured users can push to the remote. 

Help links:
- https://www.eclipse.org/che/docs/che-7/hosted-che.html#prerequisites-5
-  https://github.com/eclipse/che-theia/tree/master/plugins/ssh-plugin
- https://youtu.be/72MDoJT05cY

**Comment by ibuziuk** [comment] 2019-07-30 11:59
@ScrewTSW @Katka92 hope you will be able to help to verify the flow against prod-preview

**Comment by ibuziuk** [comment] 2019-07-30 14:19
cc: @vparfonov

**Comment by ScrewTSW** [comment] 2019-07-30 14:47
Pubkey doesn't work right after generating
Pubkey works after workspace restart (can authorize git)

**Comment by ibuziuk** [comment] 2019-07-30 15:57
Upstream issue has been created - https://github.com/eclipse/che/issues/14073

**Comment by ScrewTSW** [comment] 2019-08-20 11:46
Issue is still being discussed in upstream. Moved to On-Hold

**Comment by ibuziuk** [comment] 2019-08-29 15:56
@ScrewTSW could you confirm that message is shown once ssh key is generated? and that ssh access work in general on prod-preview?

**Comment by ScrewTSW** [comment] 2019-08-30 10:12
> @ScrewTSW could you confirm that message is shown once ssh key is generated? and that ssh access work in general on prod-preview?

![image](https://user-images.githubusercontent.com/16451875/64004278-39ba4480-cb0e-11e9-8144-082818609f48.png)

It seems to be working just as expected, so it's :+1: from me.

**Comment by ibuziuk** [comment] 2019-08-30 10:26
@ScrewTSW great, so git push / pull works just fine?

**Comment by ScrewTSW** [comment] 2019-08-30 11:26
![image](https://user-images.githubusercontent.com/16451875/64017364-bad30500-cb29-11e9-8332-05133c05e5ff.png)

Everything works as intended. Closing

**Closed by ScrewTSW** 2019-08-30 11:26 UTC
Labels: kind/task, team/rhche-qe
